var recs = [
    {
        title: 'Mage & Demon Queen',
        Rating: 1,
        link: ['Other','https://www.webtoons.com/en/comedy/mage-and-demon-queen/list?title_no=1438&page=1'],
        media: 'comic/manga',
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'speculative', 'f/f', 'female protag', 'unseen', ],
        notes: 'Very silly, more fanservice than romance',
    },
    {
        title: 'Glittermitten Cove',
        Rating: 2,
        link: ['Other',''],
        media: 'game: puzzle',
        mood: ['happy', ],
        tags: ['speculative', 'low plot', ],
        notes: 'on Steam',
    },
    {
        title: 'tametsi',
        Rating: 3,
        link: ['Other',''],
        media: 'game: puzzle', 
        mood: ['happy', ],
        tags: ['low plot', 'seen', ],
        notes: 'steam',
    },
    {
        title: 'verdant skies',
        Rating: 3,
        link: ['Other',''],
        media: 'game: exploration', 
        mood: ['happy', 'fluff', ],
        tags: ['romance', 'speculative', 'cheesy', 'f/f', 'm/m', 'nb', 'polyamory', 'seen', ],
        notes: 'steam',
    },
    {
        title: 'She-ra',
        Rating: 4,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: cartoon',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'comedy', 'childrens', 'speculative', 'f/f', 'finish it',],
        notes: '',
    },

]

var bookshelf = [
    {
        title: 'YOU’RE MY GLORY',
        Rating: 2,
        link: ['Other','https://hui3r.wordpress.com/gu-man/'],
        media: 'book', 
        mood: ['happy', ],
        tags: ['romance', 'female protag', ],
        notes: '',
    },
    {
        title: 'Transmigrated Into a Big Boss to Snatch Away the Cannon Fodder',
        Rating: 2,
        link: ['Other','https://www.novelupdates.com/series/transmigrated-into-a-big-boss-to-snatch-away-the-cannon-fodder/?pg=3'],
        media: 'book', 
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'm/m', 'unseen', ],
        notes: 'unfinished translation',
    },
    {
        title: 'PUBG Online Romance of the Century',
        Rating: 2,
        link: ['Other','https://chrysanthemumgarden.com/novel-tl/pubg/'],
        media: 'book', 
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'm/m', 'unseen', ],
        notes: 'unfinished translation',
    },
    {
        title: 'Very Happy',
        Rating: 2,
        link: ['Other',''],
        media: 'book', 
        mood: ['happy', ],
        tags: ['romance', 'm/m', 'unseen', ],
        notes: 'cnovel',
    },
    {
        title: 'Later He Became A Royal Healer',
        Rating: 2,
        link: ['Other',''],
        media: 'book', 
        mood: ['happy', ],
        tags: ['romance', 'm/m', 'unseen', ],
        notes: '',
    },
    {
        title: 'Two Dots',
        Rating: 2,
        link: ['Other',''],
        media: 'game: puzzle', 
        mood: [],
        tags: ['unseen', ],
        notes: 'phone game',
    },
    {
        title: 'I Love Hue',
        Rating: 2,
        link: ['Other',''],
        media: 'game: puzzle', 
        mood: [],
        tags: ['unseen', ],
        notes: 'phone game',
    },
    {
        title: '1010!',
        Rating: 2,
        link: ['Other',''],
        media: 'game: puzzle', 
        mood: [],
        tags: ['unseen', ],
        notes: 'phone game',
    },
    {
        title: 'Alter Ego',
        Rating: 3,
        link: ['Other',''],
        media: 'game: puzzle', 
        mood: [],
        tags: ['unseen', ],
        notes: 'phone game',
    },
    {
        title: 'The Frostrune',
        Rating: 3,
        link: ['Other',''],
        media: 'game: puzzle', 
        mood: [],
        tags: ['adventure', 'unseen', ],
        notes: 'phone game',
    },
    {
        title: 'Agent A',
        Rating: 3,
        link: ['Other',''],
        media: 'game: puzzle', 
        mood: [],
        tags: ['action', 'unseen', ],
        notes: 'phone game',
    },
    {
        title: 'Another Eden',
        Rating: 3,
        link: ['Other',''],
        media: 'game: fighting', 
        mood: [],
        tags: ['action', 'unseen', ],
        notes: 'phone game',
    },
    {
        title: 'design for living',
        Rating: 3,
        link: ['Other',''],
        media: 'movie', 
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'unseen', 'to buy', ],
        notes: 'ot3-ish',
    },
    {
        title: 'bound',
        Rating: 3,
        link: ['Other',''],
        media: 'movie', 
        mood: ['bittersweet', ],
        tags: ['action', 'f/f', 'female protag', 'unseen', 'to buy', ],
        notes: 'on itunes',
    },
    {
        title: 'birds of prey',
        Rating: 3,
        link: ['Other',''],
        media: 'movie', 
        mood: ['happy', ],
        tags: ['action', 'comedy', 'speculative', 'female protag', 'unseen', 'to buy', ],
        notes: 'on itunes',
    },
    {
        title: 'Wotakoi',
        Rating: 3,
        link: ['Other',''],
        media: 'comic/manga', 
        mood: ['happy', ],
        tags: ['female protag', 'unseen','romance', 'comedy', 'to buy', ],
        notes: 'manga',
    },
    {
        title: 'oceans 8',
        Rating: 3,
        link: ['Other',''],
        media: 'movie', 
        mood: ['happy', ],
        tags: ['action', 'female protag', 'unseen', 'to buy', ],
        notes: 'on itunes',
    },
    {
        title: 'What Did You Eat Yesterday?',
        Rating: 2,
        link: ['Other',''],
        media: 'comic/manga', 
        mood: ['happy', 'bittersweet', ],
        tags: ['m/m', 'unseen', 'to buy', ],
        notes: 'manga',
    },
    {
        title: 'Criers War',
        Rating: 3,
        link: ['Other',''],
        media: 'book', 
        mood: [],
        tags: ['romance', 'action', 'speculative', 'unseen', 'to buy','f/f' ,"female protag"],
        notes: '',
    },
    {
        title: 'Don’t Pick Up Boyfriends From the Trash Bin',
        Rating: 3,
        link: ['Other','https://chrysanthemumgarden.com/novel-tl/dpubftb/'],
        media: 'book', 
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'speculative', 'm/m', 'unseen', ],
        notes: '',
    },

    {
        title: "Gravity Falls", 
        Rating: 3, 
        link: ["Disney Plus","https://www.disneyplus.com/watchlist"], 
        media: "tv: cartoon",
        mood: ["happy",],
        tags: ["comedy", "childrens","speculative","adventure",],
        notes: "No notes",
    },
    {
        title: 'Gargoyles',
        Rating: 3,
        link: ['Disney Plus','https://www.disneyplus.com/watchlist'],
        media: 'tv: cartoon',
        mood: [],
        tags: ['action', 'childrens', 'speculative', "seen","adventure",],
        notes: '',
    },
    {
        title: 'Hocus Pocus',
        Rating: 2,
        link: ['Disney Plus','https://www.disneyplus.com/watchlist'],
        media: 'movie',
        mood: ['happy'],
        tags: ['horror', 'childrens', "cheesy","unseen",],
        notes: '',
    },
    {
        title: 'Splash',
        Rating: 4,
        link: ['Disney Plus','https://www.disneyplus.com/watchlist'],
        media: 'movie',
        mood: ['happy', ],
        tags: ['romance', 'speculative', "seen",],
        notes: '',
    },
    {
        title: 'High School Musical',
        Rating: 2,
        link: ['Disney Plus','https://www.disneyplus.com/watchlist'],
        media: 'movie',
        mood: ['happy', ],
        tags: ['comedy', 'childrens', 'cheesy', "unseen",],
        notes: '',
    },
    {
        title: 'The Little Mermaid',
        Rating: 3,
        link: ['Disney Plus','https://www.disneyplus.com/watchlist'],
        media: 'movie',
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'childrens', 'speculative', 'seen',"female protag", ],
        notes: '',
    },
    {
        title: 'The Rescuers',
        Rating: 2,
        link: ['Disney Plus','https://www.disneyplus.com/watchlist'],
        media: 'movie',
        mood: ['happy', ],
        tags: ['childrens',"unseen", "adventure",],
        notes: '',
    },
    {
        title: 'The Hunchback of Notre Dame',
        Rating: 2,
        link: ['Disney Plus','https://www.disneyplus.com/watchlist'],
        media: 'movie',
        mood: ['happy', ],
        tags: ['childrens', "unseen",],
        notes: '',
    },
    {
        title: 'Coco',
        Rating: 3,
        link: ['Disney Plus','https://www.disneyplus.com/watchlist'],
        media: 'movie',
        mood: ['happy', ],
        tags: ['childrens',"unseen", ],
        notes: '',
    },
    {
        title: 'The Mandalorian',
        Rating: 5,
        link: ['Disney Plus','https://www.disneyplus.com/watchlist'],
        media: 'tv: liveaction',
        mood: ['dark', ],
        tags: ['action', 'speculative', "adventure",],
        notes: '',
    },
    {
        title: 'Claymore',
        Rating: 2,
        link: ['AnimeLab','https://www.animelab.com/shows/mine'],
        media: 'tv: anime',
        mood: ['dark', ],
        tags: ['action', 'speculative', "bittersweet","unseen","female protag","adventure",],
        notes: '',
    },
    {
        title: 'Scrapped Princess',
        Rating: 2,
        link: ['AnimeLab','https://www.animelab.com/shows/mine'],
        media: 'tv: anime',
        mood: ['dark', ],
        tags: ['action', 'speculative', "bittersweet","unseen","female protag","adventure",],
        notes: '',
    },
    {
        title: 'Spice and Wolf',
        Rating: 2,
        link: ['AnimeLab','https://www.animelab.com/shows/mine'],
        media: 'tv: anime',
        mood: [],
        tags: ['speculative', 'unseen',"adventure",],
        notes: '',
    },
    {
        title: 'Ace Attorney Movie',
        Rating: 2,
        link: ['AnimeLab','https://www.animelab.com/shows/mine'],
        media: 'movie',
        mood: ['happy', ],
        tags: ['comedy', 'cheesy', 'unseen', 'subtitled live', ],
        notes: '',
    },
    {
        title: 'Michiko and Hatchin',
        Rating: 3,
        link: ['AnimeLab','https://www.animelab.com/shows/mine'],
        media: 'tv: anime',
        mood: ['dark', 'bittersweet', ],
        tags: ['action', 'comedy', 'speculative', "female protag","adventure",'finish it',],
        notes: '',
    },
    {
        title: 'Sailor Moon',
        Rating: 2,
        link: ['AnimeLab','https://www.animelab.com/shows/mine'],
        media: 'tv: anime',
        mood: ['happy', ],
        tags: ['action', 'comedy', 'childrens', 'speculative', 'cheesy', 'f/f', 'female protag', "adventure",],
        notes: '',
    },
    {
        title: 'Card Captor Sakura',
        Rating: 2,
        link: ['AnimeLab','https://www.animelab.com/shows/mine'],
        media: 'tv: anime',
        mood: ['happy', ],
        tags: ['action', 'comedy', 'childrens', 'speculative', 'seen', 'm/m', 'female protag', "adventure",],
        notes: '',
    },
    {
        title: 'Last Exile',
        Rating: 2,
        link: ['AnimeLab','https://www.animelab.com/shows/mine'],
        media: 'tv: anime',
        mood: [],
        tags: ['romance', 'action', 'speculative', "adventure",],
        notes: '',
    },
    {
        title: 'Lovely Complex',
        Rating: 5,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'female protag', ],
        notes: '',
    },
    {
        title: 'Keep Your Hands Off Eizouken!',
        Rating: 5,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', ],
        tags: ['comedy', 'female protag', ],
        notes: '',
    },
    {
        title: 'Skull-face Bookseller Honda-san',
        Rating: 3,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', ],
        tags: ['comedy', "low plot",],
        notes: '',
    },
    {
        title: 'Magia Record: Puella Magi Madoka Magica Side Story',
        Rating: 2,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['sad', 'scary', 'dark', 'bittersweet', ],
        tags: ['action', 'speculative', 'female protag', ],
        notes: '',
    },
    {
        title: 'Sarazanmai',
        Rating: 4,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['bittersweet', ],
        tags: ['action', 'comedy', 'speculative', 'm/m', 'finish it',],
        notes: '',
    },
    {
        title: 'ROOM CAMP',
        Rating: 3,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', 'fluff', ],
        tags: ['comedy', 'female protag', "low plot",],
        notes: '',
    },

    {
        title: 'Ascendance of a Bookworm',
        Rating: 2,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', ],
        tags: ['adventure', 'female protag', ],
        notes: '',
    },
    {
        title: 'Hakata Tonkotsu Ramens',
        Rating: 3,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', 'dark', 'bittersweet', ],
        tags: ['action', 'comedy', ],
        notes: '',
    },
    {
        title: 'Tsuritama',
        Rating: 3,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', 'bittersweet', ],
        tags: ['adventure', 'comedy', 'speculative', ],
        notes: '',
    },
    {
        title: 'Hunter x Hunter',
        Rating: 3,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: [],
        tags: ['action', 'adventure', 'speculative', ],
        notes: '',
    },
    {
        title: 'Bungo Stray Dogs',
        Rating: 2,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['bittersweet', ],
        tags: ['action', 'adventure', 'speculative', ],
        notes: '',
    },

    {
        title: 'Yona of the Dawn',
        Rating: 3,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', 'bittersweet', ],
        tags: ['romance', 'action', 'adventure', 'speculative', 'female protag', ],
        notes: '',
    },
    {
        title: 'SKET Dance',
        Rating: 2,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', ],
        tags: ['comedy', ],
        notes: '',
    },
    {
        title: 'That time I got Reincarnated as A Slime',
        Rating: 2,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'comedy', 'speculative', ],
        notes: '',
    },
    {
        title: 'Gintama',
        Rating: 4,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'comedy', 'speculative', ],
        notes: 'Guide: https://nemicon.dreamwidth.org/4516.html',
    },
    {
        title: 'Time of Eve',
        Rating: 3,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['bittersweet', ],
        tags: ['speculative', ],
        notes: '',
    },
    {
        title: 'RIN-NE',
        Rating: 2,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'speculative', 'female protag', ],
        notes: '',
    },
    {
        title: 'Yamada-kun and the Seven Witches',
        Rating: 3,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'speculative', ],
        notes: '',
    },
    {
        title: 'Is the Order a Rabbit?',
        Rating: 3,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', 'fluff', ],
        tags: ['comedy', 'female protag', "low plot",],
        notes: '',
    },
    {
        title: 'Log Horizon',
        Rating: 2,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: [],
        tags: ['action', 'adventure', ],
        notes: '',
    },
    {
        title: 'Flying Witch',
        Rating: 4,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', 'fluff', ],
        tags: ['comedy', 'female protag', "low plot",],
        notes: '',
    },
    {
        title: 'NEW GAME!',
        Rating: 3,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', 'fluff', ],
        tags: ['comedy', 'female protag', "low plot",],
        notes: '',
    },
    {
        title: 'sweetness & lightning',
        Rating: 4,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', 'fluff', "low plot",'finish it',],
        tags: ['comedy', ],
        notes: '',
    },
    {
        title: 'RWBY',
        Rating: 2,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'comedy', 'speculative', ],
        notes: '',
    },
    {
        title: 'The Ancient Magus Bride',
        Rating: 4,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['bittersweet', ],
        tags: ['horror', 'action', 'adventure', 'speculative', 'female protag','finish it', ],
        notes: '',
    },
    {
        title: 'Ms. Vampire who lives in my neighborhood',
        Rating: 3,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', 'fluff', ],
        tags: ['comedy', 'speculative', 'f/f', 'female protag', "low plot",],
        notes: '',
    },
    {
        title: 'BanG Dream!',
        Rating: 2,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', 'fluff', ],
        tags: ['comedy', 'speculative', 'unseen', 'f/f', 'female protag', ],
        notes: '',
    },
    {
        title: 'Chihayafuru',
        Rating: 3,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: ['happy', ],
        tags: ['comedy', 'female protag', ],
        notes: '',
    },
    {
        title: 'gen:LOCK',
        Rating: 2,
        link: ['Crunchyroll','https://www.crunchyroll.com/home/queue'],
        media: 'tv: anime',
        mood: [],
        tags: ['action', 'adventure', 'speculative', 'unseen', ],
        notes: '',
    },
    {
        title: 'I am not ok with this',
        Rating: 2,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: liveaction',
        mood: ['bittersweet', ],
        tags: ['action', 'speculative', 'unseen', 'female protag', ],
        notes: '',
    },
    {
        title: 'Carole and Tuesday',
        Rating: 3,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: anime',
        mood: ['happy', ],
        tags: ['adventure', 'speculative', 'unseen', 'female protag', ],
        notes: '',
    },
    {
        title: 'Booksmart',
        Rating: 5,
        link: ['Other',''],
        media: 'movie',
        mood: ['happy', ],
        tags: ['comedy', 'unseen', 'female protag', ],
        notes: '',
    },
    {
        title: 'professor marston and the wonder women',
        Rating: 4,
        link: ['Other',''],
        media: 'movie',
        mood: ['happy', ],
        tags: ['unseen', 'f/f', ],
        notes: '',
    },
    {
        title: 'Mooonlight',
        Rating: 4,
        link: ['Other',''],
        media: 'movie',
        mood: ['bittersweet', ],
        tags: ['romance', 'unseen', 'm/m', ],
        notes: '',
    },
    {
        title: 'Game Night',
        Rating: 4,
        link: ['Other',''],
        media: 'movie',
        mood: ['happy', 'dark', ],
        tags: ['action', 'comedy', 'unseen', ],
        notes: '',
    },
    {
        title: 'Utena Movie',
        Rating: 3,
        link: ['Other','https://www.youtube.com/watch?v=bJguqxjzTVg&feature=youtu.be&t=3332'],
        media: 'movie',
        mood: ['bittersweet', ],
        tags: ['romance', 'adventure', 'speculative', 'seen', 'f/f', ],
        notes: '',
    },
    {
        title: 'My Neighbour Totoro',
        Rating: 3,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'movie',
        mood: ['happy', 'bittersweet', ],
        tags: ['adventure', 'childrens', 'speculative', 'seen', 'female protag', ],
        notes: '',
    },
    {
        title: 'Little Witch Academia',
        Rating: 3,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: anime',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'comedy', 'childrens', 'speculative', 'female protag', ],
        notes: '',
    },
    {
        title: 'Detective Pikachu',
        Rating: 4,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'movie',
        mood: ['happy', ],
        tags: ['adventure', 'comedy', 'childrens', 'speculative', "unseen",'finish it',],
        notes: '',
    },
    {
        title: 'Violet Evergarden',
        Rating: 3,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: anime',
        mood: ['bittersweet', ],
        tags: ['action', 'adventure', 'speculative', 'female protag',"unseen", ],
        notes: '',
    },
    {
        title: 'Hilda',
        Rating: 3,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: cartoon',
        mood: ['happy', 'fluff', ],
        tags: ['adventure', 'comedy', 'childrens', 'speculative', 'female protag', ],
        notes: '',
    },
    {
        title: 'The Good Place',
        Rating: 3,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: liveaction',
        mood: ['happy', ],
        tags: ['adventure', 'comedy', 'speculative', 'female protag', ],
        notes: '',
    },
    {
        title: 'Your Name',
        Rating: 3,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'movie',
        mood: ['bittersweet', ],
        tags: ['romance', 'speculative', 'female protag', ],
        notes: '',
    },
    {
        title: 'Kakagerui',
        Rating: 3,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: anime',
        mood: ['happy', 'dark', ],
        tags: ['adventure', 'f/f', ],
        notes: '',
    },
    {
        title: 'Derry Girls',
        Rating: 3,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: liveaction',
        mood: ['happy', ],
        tags: ['comedy', 'female protag', ],
        notes: '',
    },
    {
        title: 'Teen Titans Go',
        Rating: 1,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: cartoon',
        mood: ['happy', ],
        tags: ['action', 'comedy', 'childrens', 'speculative', 'unseen', "cheesy"],
        notes: '',
    },
    {
        title: 'The Castle of Cagliostro',
        Rating: 2,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'movie',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'comedy', 'seen', ],
        notes: '',
    },
    {
        title: 'Shazam',
        Rating: 2,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'movie',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'comedy', 'childrens', "unseen",],
        notes: '',
    },
    {
        title: 'Black Lagoon',
        Rating: 3,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: anime',
        mood: ['bittersweet', ],
        tags: ['action', 'adventure', ],
        notes: '',
    },
    {
        title: 'The Witcher',
        Rating: 3,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: liveaction',
        mood: ['violent', 'bittersweet', ],
        tags: ['action', 'adventure', 'speculative', 'unseen', ],
        notes: '',
    },
    {
        title: 'Pokemon',
        Rating: 2,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: anime',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'comedy', 'speculative', 'unseen', ],
        notes: '',
    },
    {
        title: 'John Wick 2',
        Rating: 2,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'movie',
        mood: ['violent', ],
        tags: ['action', 'adventure', 'unseen', ],
        notes: '',
    },
    {
        title: '3 Below',
        Rating: 3,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: cartoon',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'comedy', 'childrens', 'unseen', ],
        notes: '',
    },
    {
        title: 'Mama Mia 2',
        Rating: 2,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'movie',
        mood: ['happy', 'fluff', ],
        tags: ['comedy', 'cheesy', 'unseen', ],
        notes: '',
    },

    {
        title: 'Young Justice',
        Rating: 2,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: cartoon',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'speculative', ],
        notes: '',
    },
    {
        title: 'Schitts Creek',
        Rating: 2,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: liveaction',
        mood: ['happy', ],
        tags: ['comedy', 'm/m', 'finish it',],
        notes: '',
    },

    {
        title: 'The Big Sick',
        Rating: 3,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'movie',
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'unseen', ],
        notes: '',
    },
    {
        title: 'My Neighbours The Yamadas',
        Rating: 2,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'movie',
        mood: ['happy', ],
        tags: ['comedy', 'childrens', ],
        notes: '',
    },
    {
        title: 'Aquaman',
        Rating: 2,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'movie',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'speculative', ],
        notes: '',
    },
    {
        title: 'Bob Ross',
        Rating: 2,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: liveaction',
        mood: ['happy', 'fluff', ],
        tags: ['low plot', ],
        notes: '',
    },
    {
        title: 'A Cinderella Story',
        Rating: 2,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'movie',
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'unseen', ],
        notes: '',
    },
    {
        title: 'Always Be My Maybe',
        Rating: 2,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'movie',
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'unseen', ],
        notes: '',
    },
    {
        title: 'Misc Standup',
        Rating: 2,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: liveaction',
        mood: ['happy', ],
        tags: ['comedy', 'low plot', 'unseen', ],
        notes: '',
    },
    {
        title: 'Blades of Glory',
        Rating: 2,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: liveaction',
        mood: ['happy', ],
        tags: ['comedy', 'cheesy', 'unseen', ],
        notes: '',
    },
    {
        title: 'Elf',
        Rating: 2,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: liveaction',
        mood: ['happy', ],
        tags: ['comedy', 'cheesy', 'unseen', ],
        notes: '',
    },
    {
        title: 'Healer',
        Rating: 3,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: liveaction',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'unseen', 'subtitled live', ],
        notes: '',
    },
    {
        title: 'Accidentally in Love',
        Rating: 2,
        link: ['Netflix','https://www.netflix.com/browse/my-list'],
        media: 'tv: liveaction',
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'subtitled live', ],
        notes: '',
    },
    {
        title: 'Everyone Thinks That I Like Him',
        Rating: 2,
        link: ['Other',''],
        media: 'book',
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'm/m', 'unseen', ],
        notes: '',
    },
    {
        title: 'Full Court Crush',
        Rating: 3,
        link: ['Other','http://www.hannahblumenreich.com/#/fullcourt-crush/'],
        media: 'comic/manga',
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'f/f', 'female protag', 'unseen', ],
        notes: '',
    },
    {
        title: 'Circuits and Veins',
        Rating: 2,
        link: ['Other','https://www.webtoons.com/en/challenge/circuits-and-veins/list?title_no=98905&page=1'],
        media: 'comic/manga',
        mood: ['happy', 'fluff', ],
        tags: ['romance', 'comedy', 'f/f', 'female protag', 'unseen', ],
        notes: '',
    },
    
    {
        title: 'Lets Play',
        Rating: 2,
        link: ['Other','https://www.webtoons.com/en/romance/letsplay/list?title_no=1218&page=1'],
        media: 'comic/manga',
        mood: ['happy', ],
        tags: ['romance', 'female protag', 'unseen', ],
        notes: '',
    },
    {
        title: 'Plain Boy & Prince',
        Rating: 2,
        link: ['Other','https://www.webtoons.com/en/challenge/plain-boy-prince/list?title_no=196498&page=1'],
        media: 'comic/manga',
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'm/m', 'unseen', ],
        notes: '',
    },
    {
        title: 'Idiots Dont Catch Colds',
        Rating: 2,
        link: ['Other','https://www.webtoons.com/en/challenge/idiots-dont-catch-colds/list?title_no=75094&page=1'],
        media: 'comic/manga',
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'm/m', 'unseen', ],
        notes: '',
    },
    {
        title: 'Ascending, Do Not Disturb',
        Rating: 2,
        link: ['Other','https://www.novelupdates.com/series/ascending-do-not-disturb/'],
        media: 'book',
        mood: ['happy', 'fluff', ],
        tags: ['romance', 'comedy', 'female protag', 'unseen', ],
        notes: '',
    },
    {
        title: 'Jiang Hu’s Road is Curved',
        Rating: 2,
        link: ['Other','https://www.novelupdates.com/series/jiang-hus-road-is-curved/'],
        media: 'book',
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'female protag', 'unseen', ],
        notes: '',
    },
    {
        title: 'Sect Leader and Little Shimeis Story',
        Rating: 2,
        link: ['Other','https://extrapenguin.dreamwidth.org/174039.html'],
        media: 'movie',
        mood: ['happy', ],
        tags: ['romance', 'cheesy', 'f/f', 'female protag', 'subtitled live', "short",],
        notes: '',
    },
    {
        title: 'Hamiltons Battalion',
        Rating: 2,
        link: ['Other',''],
        media: 'book',
        mood: ['happy', ],
        tags: ['romance', 'female protag', 'unseen',  "short",],
        notes: 'on Kobo, iBooks',
    },
    {
        title: 'The Cinderella Deal',
        Rating: 3,
        link: ['Other',''],
        media: 'book',
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'female protag', 'unseen', ],
        notes: 'on Kobo',
    },
    {
        title: 'Stardust',
        Rating: 2,
        link: ['Other',''],
        media: 'book',
        mood: ['happy', ],
        tags: ['romance', 'female protag', 'unseen', ],
        notes: 'on Kobo. Astronomers.',
    },
    {
        title: 'A Thousand Words For Stranger',
        Rating: 2,
        link: ['Other',''],
        media: 'book',
        mood: ['happy', ],
        tags: ['romance', 'speculative', 'female protag', 'unseen', ],
        notes: 'on Kobo',
    },
    {
        title: 'Caught in Amber',
        Rating: 2,
        link: ['Other',''],
        media: 'book',
        mood: ['happy', ],
        tags: ['romance', 'speculative', 'female protag', 'unseen', ],
        notes: 'on Kobo',
    },
    {
        title: 'Vivid',
        Rating: 2,
        link: ['Other',''],
        media: 'book',
        mood: ['happy', ],
        tags: ['romance', 'female protag', 'unseen', ],
        notes: 'on Kobo',
    },
    {
        title: 'The Black Lily',
        Rating: 2,
        link: ['Other',''],
        media: 'book',
        mood: ['happy', ],
        tags: ['romance', 'speculative', 'female protag', 'unseen', ],
        notes: 'on iBooks',
    },
    {
        title: 'Faith',
        Rating: 2,
        link: ['Other',''],
        media: 'comic/manga',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'speculative', 'female protag', 'unseen', ],
        notes: 'on iBooks',
    },
    {
        title: 'The Godstalker Chronicles',
        Rating: 3,
        link: ['Other',''],
        media: 'book',
        mood: [],
        tags: ['action', 'adventure', 'speculative', 'female protag', 'unseen', ],
        notes: 'on iBooks',
    },
    {
        title: 'Skin Folk',
        Rating: 3,
        link: ['Other',''],
        media: 'book',
        mood: ['bittersweet', ],
        tags: ['action', 'adventure', 'speculative', 'female protag', 'unseen', ],
        notes: 'on iBooks. Short stories.',
    },
    {
        title: 'The Death Of The Necromancer',
        Rating: 3,
        link: ['Other',''],
        media: 'book',
        mood: ['bittersweet', ],
        tags: ['action', 'adventure', 'speculative', 'unseen', ],
        notes: 'on iBooks',
    },
    {
        title: 'The Hero And The Crown',
        Rating: 3,
        link: ['Other',''],
        media: 'book',
        mood: ['bittersweet', ],
        tags: ['action', 'adventure', 'childrens', 'speculative', 'unseen', ],
        notes: 'on iBooks',
    },
    {
        title: 'The Mystic Marriage',
        Rating: 2,
        link: ['Other',''],
        media: 'book',
        mood: [],
        tags: ['action', 'adventure', 'childrens', 'speculative', 'f/f', 'female protag', 'unseen', ],
        notes: 'on iBooks',
    },
    {
        title: 'The Trouble With Grace',
        Rating: 2,
        link: ['Other',''],
        media: 'book',
        mood: ['happy', ],
        tags: ['romance', 'adventure', 'female protag', 'unseen', ],
        notes: 'on iBooks',
    },
    {
        title: 'Magical Otoge Ciel',
        Rating: 2,
        link: ['Other',''],
        media: 'game: Visual Novel',
        mood: ['happy', ],
        tags: ['romance', 'action', 'adventure', 'comedy', 'speculative', 'female protag', ],
        notes: '',
    },
    {
        title: 'Magical Diary: Wolf Hall',
        Rating: 3,
        link: ['Other',''],
        media: 'game: Visual Novel',
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'speculative', 'm/m', 'to buy', ],
        notes: '',
    },
    {
        title: 'Dark Nights',
        Rating: 2,
        link: ['Other',''],
        media: 'game: Visual Novel',
        mood: ['bittersweet', ],
        tags: ['romance', 'speculative', 'female protag', 'to buy', ],
        notes: '',
    },
    {
        title: 'Scrambled: Syd City',
        Rating: 2,
        link: ['Other',''],
        media: 'game: Visual Novel',
        mood: ['happy', ],
        tags: ['romance', 'action', 'adventure', 'speculative', 'f/f', 'female protag', 'unseen', ],
        notes: '',
    },
    {
        title: 'Dorakone',
        Rating: 2,
        link: ['Other',''],
        media: 'game: Visual Novel',
        mood: ['happy', 'fluff', ],
        tags: ['romance', 'comedy', 'f/f', 'female protag', 'unseen', ],
        notes: '',
    },
    {
        title: 'The Ladys Choice',
        Rating: 2,
        link: ['Other',''],
        media: 'game: Visual Novel',
        mood: ['happy', ],
        tags: ['romance', 'female protag', 'unseen', 'to buy', ],
        notes: '',
    },
    {
        title: 'Heaven Will Be Mine',
        Rating: 3,
        link: ['Other',''],
        media: 'game: Visual Novel',
        mood: ['bittersweet', ],
        tags: ['romance', 'speculative', 'f/f', 'female protag', ],
        notes: '',
    },
    {
        title: 'Various cute free femslash games',
        Rating: 2,
        link: ['Other','https://nomnomnami.itch.io/'],
        media: 'game: Visual Novel',
        mood: ['happy', 'fluff', ],
        tags: ['romance', 'speculative', 'f/f', 'female protag', ],
        notes: '',
    },
    {
        title: 'Oceanic Hearts',
        Rating: 2,
        link: ['Other','https://krispycat.itch.io/oceanic-hearts'],
        media: 'game: Visual Novel',
        mood: ['happy', 'fluff', ],
        tags: ['romance', 'speculative', 'f/f', 'female protag', "polyamory",],
        notes: '',
    },
    {
        title: 'Ghosts of Miami',
        Rating: 2,
        link: ['Other','https://pillowfight.itch.io/ghosts-of-miami'],
        media: 'game: Visual Novel',
        mood: ['happy', ],
        tags: ['romance', 'adventure', 'mystery', 'f/f', 'female protag', 'unseen', ],
        notes: '',
    },
    {
        title: 'Night In The Woods',
        Rating: 3,
        link: ['Other',''],
        media: 'game: exploration',
        mood: ['bittersweet', ],
        tags: ['action', 'adventure', 'comedy', 'speculative', 'female protag', 'unseen', ],
        notes: '',
    },
    {
        title: 'The Frog Detective',
        Rating: 2,
        link: ['Other',''],
        media: 'game: exploration',
        mood: ['happy', 'fluff', ],
        tags: ['mystery', 'comedy', 'speculative', ],
        notes: '',
    },
    {
        title: 'GENDERWRECKED',
        Rating: 2,
        link: ['Other',''],
        media: 'game: Visual Novel',
        mood: ['dark', 'bittersweet', ],
        tags: ['horror', 'comedy', 'speculative', 'f/f', 'm/m', 'nb','female protag', 'unseen', ],
        notes: '',
    },
    {
        title: 'Milkmaid of the Milky Way',
        Rating: 3,
        link: ['Other',''],
        media: 'game: Visual Novel',
        mood: ['happy', ],
        tags: ['adventure', 'mystery', 'speculative', 'female protag', 'unseen', ],
        notes: '',
    },
    {
        title: 'A Short Hike',
        Rating: 3,
        link: ['Other',''],
        media: 'game: exploration',
        mood: ['happy', 'fluff', ],
        tags: ['adventure', 'female protag', 'unseen', ],
        notes: 'on Steam',
    },
    {
        title: 'Micron',
        Rating: 2,
        link: ['Other','https://apparitiongames.itch.io/micron'],
        media: 'game: puzzle',
        mood: ['happy', ],
        tags: ['low plot', 'unseen', 'to buy', ],
        notes: '',
    },
    {
        title: 'first date/cant relate',
        Rating: 2,
        link: ['Other','https://ub4q.itch.io/first-date'],
        media: 'game: Visual Novel',
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'cheesy', 'unseen', 'short',],
        notes: '',
    },
    {
        title: 'My Lil Fanfic',
        Rating: 2,
        link: ['Other','https://ub4q.itch.io/my-lil-fanfic'],
        media: 'game: Visual Novel',
        mood: ['happy', ],
        tags: ['comedy', 'unseen', 'short',],
        notes: '',
    },
    {
        title: 'A TAVERN FOR TEA',
        Rating: 2,
        link: ['Other','https://npckc.itch.io/a-tavern-for-tea'],
        media: 'game: Visual Novel',
        mood: ['happy', 'fluff', ],
        tags: ['short', ],
        notes: '',
    },
    {
        title: 'Cupid',
        Rating: 2,
        link: ['Other','https://fervent.itch.io/cupidvn'],
        media: 'game: Visual Novel',
        mood: ['dark', 'bittersweet', ],
        tags: ['horror', 'mystery', 'speculative', 'female protag', 'unseen', ],
        notes: '',
    },
    {
        title: 'LATER ALLIGATOR',
        Rating: 3,
        link: ['Other','https://fervent.itch.io/cupidvn'],
        media: 'game: Visual Novel',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'comedy', 'speculative', 'unseen', ],
        notes: 'on Steam',
    },
    {
        title: 'Baba is You',
        Rating: 3,
        link: ['Other','https://hempuli.itch.io/baba'],
        media: 'game: puzzle',
        mood: ['happy', ],
        tags: ['low plot', 'unseen', ],
        notes: '',
    },
    {
        title: 'Like Roots In The Soil',
        Rating: 3,
        link: ['Other','https://spacebackyard.itch.io/like-roots-in-the-soil'],
        media: 'game: exploration',
        mood: ['happy', ],
        tags: ['low plot', 'unseen', ],
        notes: '',
    },
    {
        title: 'Mnemonic Devices',
        Rating: 2,
        link: ['Other','https://harlevin.itch.io/mnemonic-devices'],
        media: 'game: Visual Novel',
        mood: ['happy', ],
        tags: ['romance', 'speculative', 'f/f', 'm/m', 'unseen', 'nb',],
        notes: '',
    },
    {
        title: 'THE ACCURSED TOWER',
        Rating: 2,
        link: ['Other','https://mousefountain.itch.io/the-accursed-tower'],
        media: 'game: Visual Novel',
        mood: ['dark', ],
        tags: ['speculative', 'short', 'unseen', ],
        notes: '',
    },
    {
        title: 'the fish market',
        Rating: 2,
        link: ['Other','https://fisho.itch.io/market'],
        media: 'game: exploration',
        mood: ['happy', 'fluff', ],
        tags: ['speculative', 'short', 'unseen', ],
        notes: '',
    },

    {
        title: 'Rusty Lake Hotel',
        Rating: 3,
        link: ['Other','https://rustylake.itch.io/rustylakehotel'],
        media: 'game: puzzle',
        mood: ['dark', 'bittersweet', ],
        tags: ['horror', 'mystery', 'speculative', 'unseen', 'to buy', ],
        notes: '',
    },
    {
        title: 'Lumin',
        Rating: 2,
        link: ['Other','https://teamlumin.itch.io/lumin'],
        media: 'game: exploration',
        mood: ['happy', ],
        tags: ['speculative', 'short', 'unseen', ],
        notes: '',
    },
    {
        title: 'The Lighthouse Keepers Treasure',
        Rating: 2,
        link: ['Other','https://stone-baked-games.itch.io/the-lighthouse-keepers-treasure'],
        media: 'game: exploration',
        mood: ['happy', ],
        tags: ['short', 'unseen', ],
        notes: '',
    },
    {
        title: 'The Tower at Tortenna',
        Rating: 2,
        link: ['Other','https://tower-team-international.itch.io/the-tower-at-tortenna'],
        media: 'game: exploration',
        mood: ['bittersweet', ],
        tags: ['mystery', 'short', 'unseen', ],
        notes: '',
    },

    {
        title: 'Expanse',
        Rating: 2,
        link: ['Other','https://ata.itch.io/expanse'],
        media: 'game: puzzle',
        mood: [],
        tags: ['mystery', 'short', 'unseen', ],
        notes: '',
    },
    {
        title: 'Sethian',
        Rating: 3,
        link: ['Other','https://gqul.itch.io/sethian'],
        media: 'game: puzzle',
        mood: [],
        tags: ['mystery', 'speculative', 'unseen', 'to buy', ],
        notes: '',
    },

    {
        title: 'Chook and Sosig Hit The Club',
        Rating: 4,
        link: ['Other','https://tookipalooki.itch.io/hit-the-club'],
        media: 'game: Visual Novel',
        mood: [],
        tags: ['comedy', 'speculative', 'short', 'unseen', ],
        notes: '',
    },
    {
        title: 'Banyu Lintar Angin',
        Rating: 2,
        link: ['Other',''],
        media: 'game: Visual Novel',
        mood: ['happy', ],
        tags: ['unseen', ],
        notes: 'on Steam',
    },
    {
        title: 'Fault: Milestone One',
        Rating: 2,
        link: ['Other',''],
        media: 'game: Visual Novel',
        mood: [],
        tags: ['action', 'adventure', 'unseen', ],
        notes: 'on Steam',
    },
    {
        title: 'The Gardens Between',
        Rating: 4,
        link: ['Other',''],
        media: 'game: puzzle',
        mood: ['happy', 'bittersweet', ],
        tags: ['speculative', ],
        notes: 'on Steam',
    },
    {
        title: 'Lego Marvel Superheroes',
        Rating: 3,
        link: ['Other',''],
        media: 'game: fighting',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'comedy', 'speculative', 'cheesy', ],
        notes: 'on Steam',
    },

    {
        title: 'Miss Fisher and the Deadly Maze',
        Rating: 2,
        link: ['Other',''],
        media: 'game: Visual Novel',
        mood: ['happy', ],
        tags: ['mystery', 'female protag',],
        notes: 'on Steam',
    },

    {
        title: 'One Shot',
        Rating: 2,
        link: ['Other',''],
        media: 'game: Visual Novel',
        mood: ['bittersweet', ],
        tags: ['action', 'adventure', 'speculative', 'female protag', ],
        notes: 'on Steam',
    },

    {
        title: 'Psychdelica of the Black Butterfly',
        Rating: 5,
        link: ['Other',''],
        media: 'game: Visual Novel',
        mood: ['bittersweet', ],
        tags: ['romance', 'speculative', 'female protag', 'finish it',],
        notes: 'on Steam',
    },
    {
        title: 'Solstice',
        Rating: 2,
        link: ['Other',''],
        media: 'game: Visual Novel',
        mood: [],
        tags: ['adventure', 'mystery', 'speculative', ],
        notes: 'on Steam',
    },
    {
        title: 'Star Wars: KOTR',
        Rating: 3,
        link: ['Other',''],
        media: 'game: fighting',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'speculative', 'f/f', ],
        notes: 'on Steam',
    },
    {
        title: 'Virginia',
        Rating: 2,
        link: ['Other',''],
        media: 'game: exploration',
        mood: ['bittersweet', ],
        tags: ['mystery', 'speculative', 'female protag','unseen', ],
        notes: 'on Steam',
    },
    {
        title: 'Various point and click adventure games on GoG',
        Rating: 2,
        link: ['Other',''],
        media: 'game: puzzle',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'mystery', 'comedy', 'speculative', 'unseen',],
        notes: '',
    },
    {
        title: 'Oxenfree',
        Rating: 2,
        link: ['Other',''],
        media: 'game: Visual Novel',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'mystery', 'speculative', 'unseen', ],
        notes: 'on GoG',
    },
    {
        title: 'Planescape Torment',
        Rating: 3,
        link: ['Other',''],
        media: 'game: exploration',
        mood: ['bittersweet', ],
        tags: ['horror', 'action', 'adventure', 'mystery', 'speculative', ],
        notes: 'on GoG',
    },
    {
        title: 'Recettear',
        Rating: 3,
        link: ['Other',''],
        media: 'game: puzzle',
        mood: ['happy', ],
        tags: ['adventure', 'speculative', 'female protag', ],
        notes: 'on GoG',
    },
    {
        title: 'Miss Sherlock',
        Rating: 3,
        link: ['Other',''],
        media: 'tv: liveaction',
        mood: ['happy', ],
        tags: ['mystery', 'female protag', 'unseen', 'subtitled live', ],
        notes: '',
    },
    {
        title: 'The Librarians',
        Rating: 2,
        link: ['Other',''],
        media: 'tv: liveaction',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'mystery', 'speculative', 'cheesy', 'unseen', ],
        notes: '',
    },
    {
        title: 'Barry',
        Rating: 3,
        link: ['Other',''],
        media: 'tv: liveaction',
        mood: ['dark', 'bittersweet', ],
        tags: ['horror', 'action', 'adventure', 'comedy', 'unseen', ],
        notes: '',
    },
    {
        title: 'Batwoman',
        Rating: 1,
        link: ['Other',''],
        media: 'tv: liveaction',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'f/f', 'female protag', 'unseen', ],
        notes: '',
    },
    {
        title: 'Future Man',
        Rating: 3,
        link: ['Other',''],
        media: 'tv: liveaction',
        mood: ['happy', 'dark', ],
        tags: ['adventure', 'comedy', 'speculative', 'unseen', ],
        notes: '',
    },
    {
        title: 'Gentleman Jack',
        Rating: 5,
        link: ['Other',''],
        media: 'tv: liveaction',
        mood: ['happy', ],
        tags: ['romance', 'f/f', 'female protag', 'finish it',],
        notes: '',
    },
    {
        title: 'Steven Universe Future',
        Rating: 5,
        link: ['Other',''],
        media: 'tv: cartoon',
        mood: ['happy', 'bittersweet', ],
        tags: ['action', 'adventure', 'comedy', 'childrens', 'f/f', 'unseen','finish it', ],
        notes: '',
    },

    {
        title: 'Islanders',
        Rating: 2,
        link: ['Other',''],
        media: 'game: puzzle',
        mood: ['happy', ],
        tags: ['speculative', 'low plot', ],
        notes: 'on Steam',
    },

    {
        title: 'She and the Light Bearer',
        Rating: 2,
        link: ['Other',''],
        media: 'game: exploration',
        mood: ['happy', 'fluff', ],
        tags: ['childrens', 'speculative', ],
        notes: 'on Steam',
    },

    {
        title: 'Ni No Kunii 2',
        Rating: 3,
        link: ['Other',''],
        media: 'game: fighting',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'speculative', ],
        notes: 'on Steam',
    },

    {
        title: 'The Banner Saga',
        Rating: 2,
        link: ['Other',''],
        media: 'game: fighting',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'speculative', 'unseen',],
        notes: 'on Steam',
    },
    {
        title: 'The Beginners Guide',
        Rating: 2,
        link: ['Other',''],
        media: 'game: exploration',
        mood: ['dark', 'bittersweet', ],
        tags: ['mystery', 'comedy', 'speculative', 'unseen', ],
        notes: 'on Steam',
    },

    {
        title: 'Cat Quest',
        Rating: 2,
        link: ['Other',''],
        media: 'game: fighting',
        mood: ['happy', ],
        tags: ['action', 'adventure', 'speculative', 'unseen', ],
        notes: 'on Steam',
    },

    {
        title: 'My Brother Rabbit',
        Rating: 3,
        link: ['Other',''],
        media: 'game: puzzle',
        mood: ['bittersweet', ],
        tags: ['action', 'adventure', 'speculative', 'unseen', ],
        notes: 'on Steam',
    },
    {
        title: 'Ozmafia',
        Rating: 3,
        link: ['Other',''],
        media: 'game: Visual Novel',
        mood: ['happy', ],
        tags: ['romance', 'speculative', ],
        notes: 'on Steam',
    },
    {
        title: 'Love 365',
        Rating: 4,
        link: ['Other',''],
        media: 'game: Visual Novel', 
        mood: ['happy', ],
        tags: ['romance', 'cheesy', 'unseen', 'to buy', ],
        notes: '',
    },
    {
        title: 'bookworm',
        Rating: 3,
        link: ['Other',''],
        media: 'game: puzzle', 
        mood: ['happy', ],
        tags: ['low plot', 'seen', ],
        notes: 'steam',
    },
    
    {
        title: 'pictopix',
        Rating: 3,
        link: ['Other',''],
        media: 'game: puzzle', 
        mood: ['happy', ],
        tags: ['low plot', 'seen', ],
        notes: 'steam',
    },
    {
        title: 'triple town',
        Rating: 2,
        link: ['Other',''],
        media: 'game: puzzle', 
        mood: ['happy', ],
        tags: ['low plot', 'seen', ],
        notes: 'steam',
    },
    {
        title: 'hexcells infinite',
        Rating: 2,
        link: ['Other',''],
        media: 'game: puzzle', 
        mood: ['happy', ],
        tags: ['low plot', 'seen', ],
        notes: 'steam',
    },
    {
        title: 'dragonquest builders',
        Rating: 2,
        link: ['Other',''],
        media: 'game: exploration', 
        mood: ['happy', ],
        tags: ['action', 'adventure', 'speculative', 'cheesy', 'female protag', 'seen', ],
        notes: 'ps4',
    },
    {
        title: 'Code Realize',
        Rating: 3,
        link: ['Other',''],
        media: 'game: Visual Novel', 
        mood: ['happy', ],
        tags: ['romance', 'adventure', 'speculative', 'female protag', 'seen', ],
        notes: 'ps4',
    },
    {
        title: 'Final Fantasy XIV',
        Rating: 3,
        link: ['Other',''],
        media: 'game: fighting', 
        mood: ['happy', 'bittersweet', ],
        tags: ['action', 'adventure', 'speculative', 'female protag', 'seen', ],
        notes: '',
    },
    {
        title: 'Exit Corners',
        Rating: 2,
        link: ['Other','http://exitcorners.com/'],
        media: 'game: puzzle', 
        mood: ['bittersweet', ],
        tags: ['mystery', 'speculative', ],
        notes: '',
    },
    {
        title: 'Monster factory',
        Rating: 4,
        link: ['Other','https://www.youtube.com/playlist?list=PLaDrN74SfdT6duuVl_8qxJ5eaaPHRX_ij'],
        media: 'movie', 
        mood: ['happy', ],
        tags: ['comedy', 'speculative', 'low plot', 'short', 'unseen', ],
        notes: '',
    },
    {
        title: 'Lets game it out',
        Rating: 4,
        link: ['Other','https://www.youtube.com/channel/UCto7D1L-MiRoOziCXK9uT5Q'],
        media: 'movie', 
        mood: ['happy', 'dark', ],
        tags: ['comedy', 'speculative', 'low plot', 'short', 'unseen', ],
        notes: '',
    },
    {
        title: 'Call me kevin',
        Rating: 3,
        link: ['Other','https://www.youtube.com/channel/UCdoPCztTOW7BJUPk2h5ttXA'],
        media: 'movie', 
        mood: ['happy', 'dark', ],
        tags: ['comedy', 'speculative', 'low plot', 'short', 'unseen', ],
        notes: '',
    },
    {
        title: 'Her Tale of Shim Chong',
        Rating: 4,
        link: ['Other','https://www.tappytoon.com/series/hershimch/1'],
        media: 'comic/manga', 
        mood: [],
        tags: ['romance', 'to buy', ],
        notes: '',
    },
    {
        title: 'The Strange Case of Starship Iris',
        Rating: 2,
        link: ['Other','https://www.podbean.com/podcast-detail/xcdxc-4b4ca/The-Strange-Case-of-Starship-Iris-Podcast'],
        media: 'podcast', 
        mood: ['scary', 'dark', 'bittersweet', ],
        tags: ['horror', 'action', 'mystery', 'speculative', 'f/f', 'female protag', 'unseen', ],
        notes: '',
    },
    {
        title: 'Witchs Heart',
        Rating: 2,
        link: ['Other','https://vgperson.com/games/witchheart.htm'],
        media: 'game: puzzle', 
        mood: ['scary', 'dark', 'bittersweet', ],
        tags: ['horror', 'mystery', 'speculative', 'female protag', 'unseen', ],
        notes: '',
    },
    {
        title: 'Dog Eat Dog',
        Rating: 2,
        link: ['Other','https://www.drivethrurpg.com/product/198050/Dog-Eat-Dog'],
        media: 'other', 
        mood: ['dark', 'bittersweet', ],
        tags: ['speculative', 'female protag', 'unseen', ],
        notes: 'POst colonial RPG',
    },
    {
        title: 'free soul by Ebine Yamaji',
        Rating: 3,
        link: ['Other',''],
        media: 'comic/manga', 
        mood: ['happy', 'fluff', ],
        tags: ['romance', 'f/f', 'female protag', 'unseen', 'to buy', ],
        notes: '',
    },
    {
        title: 'Renai Manga by Naoko Kodama',
        Rating: 3,
        link: ['Other',''],
        media: 'comic/manga', 
        mood: ['happy', 'fluff', ],
        tags: ['romance', 'f/f', 'female protag', 'unseen', 'to buy', ],
        notes: '',
    },
    {
        title: 'el goonish shiv',
        Rating: 2,
        link: ['Other','https://www.egscomics.com/'],
        media: 'comic/manga', 
        mood: ['happy', ],
        tags: ['romance', 'comedy', 'speculative', 'f/f', 'nb', 'polyamory', 'female protag', 'unseen', ],
        notes: '',
    },
    {
        title: 'princess jellyfish',
        Rating: 3,
        link: ['Other',''],
        media: 'comic/manga', 
        mood: ['happy', ],
        tags: ['comedy', 'female protag', ],
        notes: '',
    },
    {
        title: 'Female General and Eldest Princess ',
        Rating: 2,
        link: ['Other','https://fgep.carrd.co/'],
        media: 'book', 
        mood: ['happy', ],
        tags: ['romance', 'action', 'adventure', 'f/f', 'female protag', ],
        notes: '',
    },
    
]