var gameshelf = [

    {
        Title: 'Mass Effect Andromeda',
        Review: 'Patchy but fun scifi rpg, separate to the main Mass Effect trilogy. M/m options are iffy except Jaal.',
        Post: '',
        Rating: 3,
        Link: [['Website','https://www.ea.com/games/mass-effect/mass-effect-andromeda'],],
        Gameplay: ['exploration', 'combat', "rpg"],
        Platform: ['Windows', 'Playstation', "Xbox"],
        Genre: ['narrative', 'romance', 'action', 'adventure', 'horror', 'science fiction', "rpg"],
        Mood: ['dark', 'bittersweet', ],
        Issues: ['death', 'violence', 'scary', 'sex/nudity', 'problematic', 'dexterity/timing', ],
        Tags: ['m/f', 'f/f', 'm/m', 'queer', 'female protag', 'gender choice', ],
    },
    {
        Title: 'Mass Effect 3',
        Review: 'Great scifi rpg, with cool characters/writing/romances. Best played as a trilogy, but if you can\'t deal with dated mechanics skip 1. Two is the most heterosexual. 3 is the queerest but is broken on Steam.',
        Post: '',
        Rating: 4,
        Link: [['Website','https://www.ea.com/games/mass-effect/mass-effect-3'],],
        Gameplay: ['exploration', 'combat',"rpg" ],
        Platform: ['Windows', ,"Xbox",],
        Genre: ['narrative', 'romance', 'action', 'adventure', 'horror', 'science fiction', ],
        Mood: ['dark', 'bittersweet', ],
        Issues: ['death', 'violence', 'scary', 'sex/nudity', 'problematic', 'dexterity/timing', ],
        Tags: ['m/f', 'f/f', 'm/m', 'queer', 'female protag', 'gender choice', ],
    },
    {
        Title: 'Mass Effect 2',
        Review: 'Great scifi rpg, with cool characters/writing/romances. Best played as a trilogy, but if you can\'t deal with dated mechanics skip 1. Two is the most heterosexual.',
        Post: '',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/901242/Mass_Effect_2_Digital_Deluxe_Edition/'],['Website','https://www.ea.com/games/mass-effect/mass-effect-2'],],
        Gameplay: ['exploration', 'combat',"rpg" ],
        Platform: ['Windows',"Xbox", ],
        Genre: ['narrative', 'romance', 'action', 'adventure', 'horror', 'science fiction', ],
        Mood: ['dark', 'bittersweet', ],
        Issues: ['death', 'violence', 'scary', 'sex/nudity', 'problematic', 'dexterity/timing', ],
        Tags: ['m/f', 'female protag', 'gender choice', ],
    },
    {
        Title: 'Mass Effect 1',
        Review: 'Great scifi rpg, with cool characters/writing/romances. Best played as a trilogy, but if you can\'t deal with dated mechanics skip this one.',
        Post: '',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/17460/Mass_Effect/'],['Website','https://www.ea.com/games/mass-effect/mass-effect'],],
        Gameplay: ['exploration', 'combat', "rpg"],
        Platform: ['Windows', 'Playstation', ],
        Genre: ['narrative', 'romance', 'action', 'adventure', 'horror', 'science fiction', ],
        Mood: ['dark', 'bittersweet', ],
        Issues: ['death', 'violence', 'scary', 'sex/nudity', 'problematic', 'dexterity/timing', ],
        Tags: ['m/f', 'f/f', 'queer', 'female protag', 'gender choice', ],
    },
    {
        Title: 'Dragon Quest Builders',
        Review: 'Fun exploration/gathering/crafting rpg. Boss battles can be hard, I got stuck 75% through. Sequel is on PC. ',
        Post: '',
        Rating: 3,
        Link: [['Website','https://dragonquest.square-enix-games.com/builders/us/'],],
        Gameplay: ['sandbox', 'crafting', 'exploration', 'combat',"rpg" ],
        Platform: ['Switch', 'Playstation', ],
        Genre: ['narrative', 'action', 'adventure', 'fantasy', ],
        Mood: ['cute', ],
        Issues: ['dexterity/timing', ],
        Tags: ['female protag', 'gender choice', ],
    },
    {
        Title: 'Code Realize',
        Review: 'A dating sim about a young woman who destroys everything she touches teaming up with a group of men (loosely based on fictional characters like Victor Frankenstein) to save Steampunk England from her mad scientist father.  Overall I really enjoyed it, and it\'s a wild, romantic, and well-made ride.',
        Post: 'https://alias-sqbr.dreamwidth.org/700020.html',
        Rating: 4,
        Link: [['Switch','https://www.nintendo.com/games/detail/code-realize-guardian-of-rebirth-switch/'],],
        Gameplay: ['visual novel', ],
        Platform: ['Switch', 'Playstation', ],
        Genre: ['narrative', 'romance', 'adventure', 'fantasy', 'science fiction', 'historical', ],
        Mood: [],
        Issues: ['death', 'violence', ],
        Tags: ['m/f', 'female protag', ],
    },
    {
        Title: 'Northanger Abbey',
        Review: 'Humourous historical dating sim with the option to play as and romance various genders.',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://spiralatlas.itch.io/northanger-abbey-the-game'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'comedy','historical' ],
        Mood: ['happy', ],
        Issues: [],
        Tags: ['m/f', 'f/f', 'm/m', 'non-binary', 'binary trans', 'queer', 'female protag', 'gender choice', 'free', ],
    },
    {
        Title: 'puzzle craft',
        Review: 'Fun gathering/townbuilding game. Sequel has gacha elements.',
        Post: '',
        Rating: 4,
        Link: [],
        Gameplay: ['crafting', 'simulation', 'exploration', 'puzzle', ],
        Platform: ['iOS', 'Android', ],
        Genre: ['fantasy', ],
        Mood: ['cute', ],
        Issues: [],
        Tags: ['low plot', ],
    },
    {
        Title: 'alphabear',
        Review: 'Cute word game. Some levels are timed.',
        Post: '',
        Rating: 4,
        Link: [],
        Gameplay: ['puzzle', ],
        Platform: ['iOS', 'Android', ],
        Genre: ['word game', ],
        Mood: ['cute', ],
        Issues: ['dexterity/timing', ],
        Tags: ['low plot', 'free', ],
    },
    {
        Title: 'neko atsume',
        Review: 'Cute game about collecting and photographing cats. Mild gacha elements.',
        Post: '',
        Rating: 4,
        Link: [],
        Gameplay: ['puzzle', ],
        Platform: ['iOS', 'Android', ],
        Genre: ['slice of life', ],
        Mood: ['happy', 'cute', 'gentle', ],
        Issues: ['gacha', ],
        Tags: ['low plot', 'free', ],
    },
    {
        Title: 'Merge Dragons',
        Review: 'Cute dragon matching game with aggressive gacha elements.',
        Post: '',
        Rating: 3,
        Link: [],
        Gameplay: ['puzzle', ],
        Platform: ['iOS', 'Android', ],
        Genre: ['fantasy', ],
        Mood: ['happy', 'cute', 'gentle', ],
        Issues: ['gacha', ],
        Tags: ['low plot', 'free', ],
    },
    {
        Title: 'Obey Me',
        Review: 'gacha based mobile dating sim, this time about being a human exchange student at a DEMON HIGHSCHOOL with HOT DEMON BROTHERS. The little I saw of the actual plot and characters seemed fine, if a bit silly, but it seemed to be 90% grinding and I did not enjoy the gameplay. ',
        Post: 'https://alias-sqbr.dreamwidth.org/811337.html',
        Rating: 1,
        Link: [],
        Gameplay: ['visual novel', ],
        Platform: ['iOS', 'Android', ],
        Genre: ['narrative', 'romance', 'comedy', 'adventure', 'fantasy', ],
        Mood: ['happy', ],
        Issues: ['cheesy', 'unplayed', 'gacha', ],
        Tags: ['m/f', 'female protag', 'free', ],
    },
    {
        Title: 'Mystic Messenger',
        Review: 'a well made and enjoyable phone based dating sim with some aspects I found annoying. Has an ambiguously romantic f/f path.',
        Post: 'https://alias-sqbr.dreamwidth.org/735679.html',
        Rating: 3,
        Link: [],
        Gameplay: ['visual novel', ],
        Platform: ['iOS', 'Android', ],
        Genre: ['narrative', 'romance', 'comedy', 'adventure', 'fantasy', 'science fiction', ],
        Mood: ['happy', 'bittersweet', ],
        Issues: ['gacha', ],
        Tags: ['m/f', 'female protag', 'free', ],
    },
    {
        Title: 'Lovestruck',
        Review: 'Various m/f, f/f and f/nb dating sim stories. Diverse and some are written well but the playstructure is very gacha-y and annoying.',
        Post: 'https://alias-sqbr.dreamwidth.org/765442.html',
        Rating: 2,
        Link: [],
        Gameplay: ['visual novel', ],
        Platform: ['iOS', 'Android', ],
        Genre: ['narrative', 'romance', 'comedy', 'adventure', 'fantasy', 'science fiction', 'historical', ],
        Mood: ['happy', 'bittersweet', ],
        Issues: ['sex/nudity', 'gacha', ],
        Tags: ['m/f', 'f/f', 'non-binary', 'queer', 'female protag', 'free', ],
    },
    {
        Title: 'Love365',
        Review: 'Various fairly formulaic m/f dating sim stories. You can buy them outright and there\'s always free ones each month, but there\'s also some gacha elements.',
        Post: 'https://alias-sqbr.dreamwidth.org/765442.html',
        Rating: 3,
        Link: [],
        Gameplay: ['visual novel', ],
        Platform: ['iOS', 'Android', ],
        Genre: ['narrative', 'romance', 'comedy', 'fantasy', 'historical', ],
        Mood: ['happy', 'bittersweet', ],
        Issues: ['non-consent', 'sex/nudity', 'problematic', 'gacha', ],
        Tags: ['m/f', 'female protag', 'free', ],
    },
    {
        Title: 'Samurai Love Ballad: Party',
        Review: 'a stand-alone phone based dating sim by Voltage Japan.  It\'s set in late 16th century Japan and all the love interests are samurai/warlords/ninja etc. There\'s a non-binary love interest.',
        Post: 'https://alias-sqbr.dreamwidth.org/771502.html',
        Rating: 4,
        Link: [],
        Gameplay: ['visual novel', ],
        Platform: ['iOS', 'Android', ],
        Genre: ['narrative', 'romance', 'comedy', 'action', 'adventure', 'fantasy', 'historical', ],
        Mood: ['happy', 'bittersweet', ],
        Issues: ['death', 'violence', 'non-consent', 'sex/nudity', 'problematic', 'gacha', ],
        Tags: ['m/f', 'non-binary', 'queer', 'female protag', 'free', ],
    },
    {
        Title: 'Helix Waltz',
        Review: 'a freemium phone game where you play as Magda, a young woman from a pseudo-European fantasy country, trying to increase her family\'s social standing by attending balls in pretty outfits and forming connections with the people there. Fun until it stopped working on my phone. Terrible translation, gacha elements. ',
        Post: 'https://alias-sqbr.dreamwidth.org/726780.html',
        Rating: 2,
        Link: [],
        Gameplay: ['sandbox', 'visual novel', "rpg"],
        Platform: ['iOS', 'Android', ],
        Genre: ['narrative', 'romance', 'comedy', 'adventure', 'fantasy', ],
        Mood: ['happy', 'mysterious', ],
        Issues: ['non-consent', 'problematic', 'gacha', ],
        Tags: ['m/f', 'f/f', 'queer', 'female protag', 'free', 'designer', ],
    },
    {
        Title: 'Love Nikki',
        Review: 'a somewhat problematic dollmaker gacha game with a very silly, shallow plot. ',
        Post: 'https://alias-sqbr.dreamwidth.org/754271.html',
        Rating: 3,
        Link: [],
        Gameplay: ['sandbox', 'simulation','visual novel',"rpg" ],
        Platform: ['iOS', 'Android', ],
        Genre: ['narrative', 'comedy', 'adventure', 'fantasy', ],
        Mood: ['happy', 'bittersweet', 'cute', ],
        Issues: ['cheesy', 'problematic', 'gacha', ],
        Tags: ['m/f', 'f/f', 'queer', 'female protag', 'free','designer', ],
    },
    {
        Title: 'Glittermitten Grove',
        Review: 'cute simulation game with a weird rpg hidden inside',
        Post: '',
        Rating: 2,
        Link: [['Itchio','https://twinbeard.itch.io/glittermitten-grove'],],
        Gameplay: ['simulation', 'exploration', 'combat', "rpg"],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['fantasy', ],
        Mood: ['mysterious', 'cute', ],
        Issues: ['cheesy', ],
        Tags: ['low plot', ],
    },
    {
        Title: 'Cardinal Chains',
        Review: 'Create paths that follow numbers in order. I didn\'t love it but had fun for a while.',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://danijmn.itch.io/cardinalchains'],],
        Gameplay: ['puzzle', ],
        Platform: ['Browser', ],
        Genre: ['logic', ],
        Mood: [],
        Issues: ['difficult', ],
        Tags: ["rj bundle","low plot"],
    },
    {
        Title: 'Arigatou, Ningen-san!',
        Review: 'Cute, silly little browser game where you wander around squishily cuddling animals.',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://michellema.itch.io/arigatou-ningen-san'],],
        Gameplay: ['point and click', ],
        Platform: ['Browser', ],
        Genre: ['comedy', 'slice of life', 'narrative'],
        Mood: ['happy', 'cute', 'gentle', ],
        Issues: [],
        Tags: ['short',"rj bundle", ],
    },
    {
        Title: 'Animal Crossing',
        Review: 'Adorable, involving game about building a community on an island. Ungendered protagonist.',
        Post: '',
        Rating: 5,
        Link: [['Switch','https://www.nintendo.com/games/detail/animal-crossing-new-horizons-switch/'],],
        Gameplay: ['sandbox', 'crafting', 'simulation', 'exploration', ],
        Platform: ['Switch', ],
        Genre: ['narrative', 'slice of life', 'adventure', 'fantasy', ],
        Mood: ['happy', 'cute', 'gentle', ],
        Issues: [],
        Tags: ['designer', 'beautiful', 'non-binary', 'female protag', 'gender choice', ],
    },
    {
        Title: 'Dragon Age: Origins',
        Review: 'First in the Dragon Age series. Great fantasy RPG with engaging writing/plots/romances.  Consider the Ultimate Edition with all the DLCs. A bit dated but has lots of mods.',
        Post: '',
        Rating: 5,
        Link: [['Steam','https://store.steampowered.com/app/47810/Dragon_Age_Origins__Ultimate_Edition/'],['GOG','https://www.gog.com/game/dragon_age_origins'],['Origin/EA','https://www.ea.com/games/dragon-age/dragon-age-2'],],
        Gameplay: ['exploration', 'combat',"rpg" ],
        Platform: ['Windows',"Xbox", "Mac",],
        Genre: ['narrative', 'romance', 'action', 'adventure', 'horror', 'fantasy', ],
        Mood: ['bittersweet', ],
        Issues: ['death', 'violence', 'scary', 'sex/nudity', 'dexterity/timing',"problematic", ],
        Tags: ['beautiful', 'm/f', 'f/f', 'm/m', 'binary trans', 'queer', 'female protag', 'gender choice', ],
    },
    {
        Title: 'Dragon Age 2',
        Review: 'Second in the Dragon Age series. Great fantasy RPG with engaging writing/plots/romances. Rushed in parts but still great. Consider the Ultimate Edition with all the DLCs. Note that the Steam version requires Origin.',
        Post: '',
        Rating: 5,
        Link: [['Origin/EA store','https://www.ea.com/games/dragon-age/dragon-age-2'],],
        Gameplay: ['exploration', 'combat',"rpg" ],
        Platform: ['Windows', ],
        Genre: ['narrative', 'romance', 'action', 'adventure', 'horror', 'fantasy', ],
        Mood: ['bittersweet', ],
        Issues: ['death', 'violence', 'scary', 'sex/nudity', 'dexterity/timing',"problematic" ],
        Tags: ['beautiful', 'm/f', 'f/f', 'm/m', 'binary trans', 'queer', 'female protag', 'gender choice', ],
    },
    {
        Title: 'Dragon Age: Inquisition',
        Review: 'Third in the Dragon Age series. Great fantasy RPG with engaging writing/plots/romances. Consider the Ultimate Edition with all the DLCs. Note that the Steam version apparently doesn\'t work.',
        Post: '',
        Rating: 5,
        Link: [['Origin/EA store','https://www.ea.com/games/dragon-age/dragon-age-inquisition'],],
        Gameplay: ['exploration', 'combat',"rpg" ],
        Platform: ['Windows', ],
        Genre: ['narrative', 'romance', 'action', 'adventure', 'horror', 'fantasy', ],
        Mood: ['bittersweet', ],
        Issues: ['death', 'violence', 'scary', 'sex/nudity', 'dexterity/timing',"problematic" ],
        Tags: ['beautiful', 'm/f', 'f/f', 'm/m', 'binary trans', 'queer', 'female protag', 'gender choice', ],
    },
    {
        Title: 'Fragments of Euclid',
        Review: 'a free puzzle game about wandering around inside Escher style rooms whose gravity changes direction every time you walk through a door. I had a lot of fun during the tutorial then was so bad at the actual puzzles I gave up (I have an appalling sense of direction at the best of times), but it was worth playing just for that "being inside an Escher drawing" feeling, especially since they did a pretty good job of capturing the aesthetic.',
        Post: '',
        Rating: 2,
        Link: [['Itchio','https://nusan.itch.io/fragments-of-euclid'],],
        Gameplay: ['exploration', 'puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['fantasy', ],
        Mood: ['mysterious', 'gentle', ],
        Issues: ['difficult', ],
        Tags: ['beautiful', 'low plot', ],
    },
    {
        Title: 'Monument Valley',
        Review: 'fantastic, beautiful, understated little phone puzzle game. You are a little girl wandering minimalist fantasy landscapes with Escher-esque topology that uses forced perspective in very creative ways. I found it fairly easy, there are a few minor timing puzzles I didn\'t always like. It reminded me a lot of Journey.',
        Post: '',
        Rating: 5,
        Link: [['iOS','https://apps.apple.com/au/app/monument-valley/id728293409'],],
        Gameplay: ['puzzle', ],
        Platform: ['iOS', ],
        Genre: ['narrative', 'fantasy', ],
        Mood: ['bittersweet', 'cute', 'gentle', ],
        Issues: ['dexterity/timing'],
        Tags: ['beautiful', ],
    },
    {
        Title: 'Horizon Zero Dawn',
        Review: 'open world action RPG that combines two games: a gently bittersweet post-apocalyptic fable about the futility of war and SHOOT ROBOT DINOSAURS WITH A BOW AND ARROW. Both games are very good but the tonal dissonance can be a bit jarring. Indigenous American groups have rightfully complained about the cultural appropriation.',
        Post: 'https://alias-sqbr.dreamwidth.org/665184.html',
        Rating: 5,
        Link: [['Steam','https://store.steampowered.com/app/1151640/Horizon_Zero_Dawn_Complete_Edition/'],['Playstation','https://www.playstation.com/en-au/games/horizon-zero-dawn-ps4/'],],
        Gameplay: ['exploration', 'combat', "rpg"],
        Platform: ['Windows', 'Playstation', ],
        Genre: ['narrative', 'action', 'adventure', 'science fiction', ],
        Mood: ['bittersweet', ],
        Issues: ['death', 'violence', 'scary', 'problematic', 'dexterity/timing', ],
        Tags: ['beautiful', ],
    },
    {
        Title: 'Planescape: Torment: Enhanced Edition',
        Review: 'A classic, beloved RPG about a man who wakes, undying, in the morgue of death-worshippers. And then dies a bunch more as he tries to figure out who he is and what\'s going on. I already bought and ran out of momentum with the original version but thought the playability tweaks might make it more fun and they have, but I still ran out of momentum.',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/466300/Planescape_Torment_Enhanced_Edition/'],['GOG','https://www.gog.com/game/planescape_torment_enhanced_edition'],],
        Gameplay: ['exploration', 'point and click', 'combat',"rpg" ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'adventure', 'mystery', 'horror', 'fantasy', ],
        Mood: ['dark', 'bittersweet', ],
        Issues: ['death', 'scary', ],
        Tags: [],
    },
    {
        Title: 'Cute Demon Crashers',
        Review: 'Cute free sex positive dating (well, friends with benefits) sim. A college girl gets to know 3 incubi and a succubus and possibly has sex with one. Strong emphasis on consent and fluffy happiness: you can say no at any time and there are no bad endings. I did the f/f path and it was endearing but a bit too sex focussed for me (which I knew it would be but THE ART WAS TOO CUTE) The demons are all aromantic, it\'s the fantasy of the perfect calm, knowledgeable, non judgemental older partner with no expectations who wants nothing for themselves but to make you happy. ',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://sugarscript.itch.io/cute-demon-crashers'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'comedy', 'slice of life', ],
        Mood: ['happy', 'cute', ],
        Issues: ['sex/nudity', ],
        Tags: ['m/f', 'f/f', 'queer', 'female protag', 'free', 'aromantic/asexual'],
    },
    {
        Title: 'Butterfly Soup',
        Review: 'a justly beloved f/nb visual novel about a group of Asian American teenage girls who join a baseball team. Not a dating sim, since your choices don\'t affect the plot but are just there for humour and immersion, but it has a really cute romance arc.',
        Post: '',
        Rating: 5,
        Link: [['Itchio','https://brianna-lei.itch.io/butterfly-soup'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'comedy', 'slice of life', ],
        Mood: ['happy', 'cute', ],
        Issues: [],
        Tags: ['f/f', 'non-binary', 'queer', 'female protag', 'free', ],
    },
    {
        Title: 'can you say my name again',
        Review: '',
        Post: '',
        Rating: 5,
        Link: [['Itchio','https://nadianova.itch.io/can-you-say-my-name-again'],],
        Gameplay: ['visual novel', ],
        Platform: ['Browser', ],
        Genre: ['narrative', 'romance', 'slice of life', ],
        Mood: ['cute', 'gentle', ],
        Issues: ['sex/nudity'],
        Tags: ['short', 'f/f', 'binary trans', 'queer', 'female protag', 'free', ],
    },
    {
        Title: 'EGG BABY',
        Review: 'Free, browser based, illustrated text game about raising fantasy eggs. Very short and random but cute.',
        Post: '',
        Rating: 2,
        Link: [['Itchio','https://splendidland.itch.io/egg-baby'],],
        Gameplay: ['simulation', ],
        Platform: ['Browser', ],
        Genre: ['fantasy', ],
        Mood: ['happy', 'cute', 'gentle', ],
        Issues: [],
        Tags: ['low plot', 'short', 'free', ],
    },
    {
        Title: 'Mermaid Splash! Passion Festival',
        Review: 'A free f/f dating/life sim about a mermaid, Cici, deciding what hobby to present at an upcoming festival. I overall enjoyed this, though some things bugged me. The art is SUPER cute, especially the character designs, with more body type diversity than you usually see and a very cute trans woman love interest. ',
        Post: 'https://alias-sqbr.dreamwidth.org/670062.html',
        Rating: 4,
        Link: [['Itchio','https://sofdelux.itch.io/mermaid-splash'],],
        Gameplay: ['simulation', 'visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', 'Android', ],
        Genre: ['narrative', 'romance', 'comedy', 'slice of life', 'fantasy', ],
        Mood: ['happy', 'cute', 'gentle', ],
        Issues: ['cheesy', ],
        Tags: ['short', 'f/f', 'queer', 'binary trans', 'free', ],
    },
    {
        Title: 'Sunbeam',
        Review: ' A free fun puzzle/exploration game about wandering an alien planet moving mirrors to activate solar panels with sunlight. I enjoyed it a lot overall but the art is super ugly (low polyamory 3D can look good but this does not) and the plot (as told my messages left around the landscape) is unfinished and a bit depressing. But if you ignore the plot and art and just do the puzzles it\'s a fun way to pass the time.',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://stone-baked-games.itch.io/sunbeam'],],
        Gameplay: ['exploration', 'puzzle'],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['science fiction','narrative' ],
        Mood: ['bittersweet', 'gentle', ],
        Issues: ['death', ],
        Tags: ['short', 'free', ],
    },
    {
        Title: 'It Will Be Hard',
        Review: 'Gentle interactive comic about a m/m couple working through relationship stuff around asexuality and polyamory.',
        Post: '',
        Rating: 4,
        Link: [['Itchio','https://wavingpeople.itch.io/it-will-be-hard'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['romance', 'slice of life', 'fantasy', 'narrative',],
        Mood: ['happy', 'cute', 'gentle', ],
        Issues: ['sex/nudity'],
        Tags: ['short', 'm/m', 'polyamory', 'queer', 'aromantic/asexual','free', ],
    },
    {
        Title: 'The Shape On The Ground',
        Review: 'a strange walking sim where you find and look at odd tableaus. Atmospheric and metaphorical though I\'m not sure what the metaphor is actually saying.',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://somewhat.itch.io/the-shape-on-the-ground'],],
        Gameplay: ['exploration', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['mystery', 'horror', 'fantasy', ],
        Mood: ['sad', 'dark', 'mysterious', ],
        Issues: ['death','violence', ],
        Tags: ['low plot', 'short', 'free', ],
    },
    {
        Title: 'Chook & Sosig',
        Review: 'A really great little charmingly dark New Zealand comedy about a talking cat and his ghost chicken friend. There\'s a whole series of these games but I haven\'t played the others yet. The art is fantastic, too, very unique and expressive.',
        Post: '',
        Rating: 5,
        Link: [['Itchio','https://tookipalooki.itch.io/chook-and-sosig'],],
        Gameplay: ['visual novel', 'point and click', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['narrative', 'comedy', 'mystery', 'horror', 'fantasy', ],
        Mood: ['dark', ],
        Issues: ['death', ],
        Tags: ['short', 'free', ],
    },
    {
        Title: 'Halloween Otome',
        Review: 'Cute silly m/f dating sim set at a fancy halloween party.',
        Post: 'https://alias-sqbr.dreamwidth.org/684887.html',
        Rating: 3,
        Link: [['Itchio','https://synokoria.itch.io/halloween-otome'],],
        Gameplay: ['visual novel', 'puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'comedy', ],
        Mood: ['happy', ],
        Issues: [],
        Tags: ['m/f', 'female protag', 'free', ],
    },
    {
        Title: 'Valentines Otome',
        Review: 'a m/f dating sim (with actual sim elements!), and is a sequel to the m/f dating sim Halloween Otome.  It was a mix of enjoyable and annoying and WEIRD.',
        Post: 'https://alias-sqbr.dreamwidth.org/684887.html',
        Rating: 2,
        Link: [['Itchio','https://synokoria.itch.io/valentines-otome'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'comedy', ],
        Mood: ['happy', ],
        Issues: ['cheesy', 'problematic', ],
        Tags: ['m/f', 'female protag', 'free', ],
    },
    
    {
        Title: 'why is this dragon so fucking cute??',
        Review: 'A cute, short, light f/f romance between a dragon hunter and the (very anthropomorphic) dragon she\'s been hired to fight.',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://nadianova.itch.io/why-is-this-dragon-so-fucking-cute'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'comedy', 'fantasy', ],
        Mood: ['happy', 'cute', ],
        Issues: ['cheesy', ],
        Tags: ['short','f/f', 'queer', 'binary trans','female protag', 'free', ],
    },
    {
        Title: 'RE: Alistair++',
        Review: 'A m/f dating sim about a hot-headed girl trying to track down the guy at her high-school who screwed her over in an online game. I quite liked one of the romances (shy sweetie Shiro) but the other two were fine for what they were but didn\'t click for me. I tried and got bored of this years ago, this time when I started getting frustrated I looked up a walkthrough and it\'s a lot more fun that way, otherwise it\'s too easy to alienate everyone and have zero interesting interactions. The art and writing were adequate.',
        Post: '',
        Rating: 4,
        Link: [['Itchio','https://sakevisual.itch.io/re-alistair'],],
        Gameplay: ['simulation', 'visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'comedy', 'slice of life', ],
        Mood: ['happy', ],
        Issues: [],
        Tags: ['m/f', 'female protag', 'free', ],
    },
    {
        Title: 'Vicarwissen',
        Review: 'A cute short horror visual novel about two Youtube paranormal investigators who are also girlfriends investigating strange events in a museum. Does have a happy ending but I died a LOT of grisly deaths getting there. Not super scary but definitely in the horror genre.',
        Post: '',
        Rating: 4,
        Link: [['Itchio','https://lazilisk.itch.io/vicarwissen'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'comedy', 'mystery', 'horror', 'fantasy', 'cute'],
        Mood: ['dark', ],
        Issues: ['death','violence', ],
        Tags: ['short', 'f/f', 'queer', 'female protag', 'free', ],
    },
    {
        Title: 'The Knife of the Traitor',
        Review: 'a silly macabre visual novel, it\'s very cheesy and rushed and feels like the people who made it were very young but I enjoyed it well enough and it\'s certainly a change from the usual. You play an amnesiac Evil Princess who\'s woken up with a knife in her throat and has to figure out which of the people who might justifiably want you dead stabbed you. The other characters are all male and there\'s romantic elements but it\'s not really a dating sim. I rolled my eyes a few times at some unfortunate choices in the writing but the art was pretty good, someone obviously had fun with the character design.',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://chegovia.itch.io/tkot'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'comedy', 'mystery', 'horror', 'fantasy', ],
        Mood: ['dark', ],
        Issues: ['violence',],
        Tags: ['m/f', 'female protag', 'free', ],
    },
    {
        Title: 'Serre',
        Review: 'f/f romance visual novel about an anti-social plant nerd and the giant bee alien who crash-lands into her greenhouse looking to conquer the planet.  It\'s exactly the sort of game it looked like on the tin: fun and sweet, but very short and with not a lot of substance. I still enjoyed it, and there was more emotional depth than I was expecting even if the plot\'s pretty cartoonish. The art is well done, with more animation and CGs than you usually get for this sort of tiny indie game. There\'s not many choices and I don\'t think they affected the plot but they added some cute moments.',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://insertdisc5.itch.io/serre'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['narrative', 'romance', 'comedy', 'science fiction', ],
        Mood: ['happy', 'cute', ],
        Issues: [],
        Tags: ['short','f/f', 'queer', 'female protag',"rj bundle",  ],
    },
    {
        Title: 'XOXO Droplets',
        Review: 'a humourous game about dating The Douchiest Guys In School. The premise put me off for a long time, since I wasn\'t sure if it would take the romances seriously, and it isn\'t as feels heavy as my favourite otome games. But under the humour are some genuine characters and sincere feelings, I spend a lot of time thinking "Haha, aww, you assholes really do deserve each other <3". Also, unlike most humourous VNs, it\'s actually funny.',
        Post: 'https://alias-sqbr.dreamwidth.org/749802.html',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/622060/XOXO_Droplets/'],['Itchio','https://gbpatch.itch.io/xoxo-droplets'],],
        Gameplay: ['simulation', 'visual novel', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['narrative', 'romance', 'comedy', 'slice of life', ],
        Mood: ['happy', 'cute', ],
        Issues: ['difficult', ],
        Tags: ['m/f', 'queer', 'female protag', 'free', ],
    },
    {
        Title: 'Loan Wolf',
        Review: 'Cute short free f/f dating sim set in a world like ours but everyone is mythological creatures. The protagonist is a werewolf who works in user support.',
        Post: '',
        Rating: 4,
        Link: [['Itchio','https://teamrumblebee.itch.io/loan-wolf'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'comedy', 'fantasy', ],
        Mood: ['happy', 'cute', ],
        Issues: [],
        Tags: ['short', 'f/f', 'queer', 'female protag', 'free', ],
    },
    {
        Title: 'Braincross',
        Review: 'Free logic puzzle browser game based on variations on picross. A little rough around the edges but I really enjoyed it!',
        Post: '',
        Rating: 4,
        Link: [['Itchio','https://zblip.itch.io/braincross'],],
        Gameplay: ['puzzle', ],
        Platform: ['Browser', ],
        Genre: ['logic',],
        Mood: [],
        Issues: [],
        Tags: [ 'low plot', 'free', ],
    },
    {
        Title: 'Pixoji',
        Review: 'Variant on picross.',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://zblip.itch.io/pixoji'],],
        Gameplay: ['puzzle', ],
        Platform: ['Android', 'Browser', ],
        Genre: ['logic',],
        Mood: [],
        Issues: [],
        Tags: [ 'low plot', 'free', ],
    },
    {
        Title: 'Solitaire',
        Review: 'Simple Solitaire.',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://fewargs.itch.io/solitaire'],],
        Gameplay: ['puzzle', ],
        Platform: ['iOS', 'Android', 'Browser', ],
        Genre: ['logic',],
        Mood: [],
        Issues: [],
        Tags: [ 'low plot', 'free', ],
    },
    {
        Title: 'Dot Connect',
        Review: 'Connect dots into lines.',
        Post: '',
        Rating: 2,
        Link: [['Itchio','https://fewargs.itch.io/lets-connect'],],
        Gameplay: ['puzzle', ],
        Platform: ['iOS', 'Android', 'Browser', ],
        Genre: ['logic',],
        Mood: [],
        Issues: [],
        Tags: [ 'low plot', 'free', ],
    },
    {
        Title: 'Dissembler',
        Review: 'A well made and pretty puzzle game about rearranging squares that didn\'t click for me because I am not very good at physical/visual thinking. I had an ok time until it got too hard for me.',
        Post: '',
        Rating: 2,
        Link: [['Itchio','https://ianmaclarty.itch.io/dissembler'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux',"Android" ],
        Genre: ['logic',],
        Mood: [],
        Issues: [],
        Tags: [ 'low plot', ],
    },
    {
        Title: 'Mister Line',
        Review: 'Draw lines in a maze.',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://zblip.itch.io/mister-line'],],
        Gameplay: ['puzzle', ],
        Platform: ['Browser', ],
        Genre: [],
        Mood: [],
        Issues: [],
        Tags: ['low plot', 'free', ],
    },
    {
        Title: 'Sacramento',
        Review: 'A tiny free walking sim, where you explore a strange place and nothing much happens. Was pretty but very slight, unless I missed something.',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://dziff.itch.io/sacramento'],],
        Gameplay: ['exploration', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: [],
        Mood: [],
        Issues: [],
        Tags: ['short','beautiful', 'low plot', 'free', ],
    },
    {
        Title: 'ryb',
        Review: 'Elegant logic puzzles. Lots of logical deductions along the lines of "Ok this circle has to touch two red shapes, and this adjacent triangle touches one red and one yellow..." ',
        Post: '',
        Rating: 5,
        Link: [['Itchio','https://fleb.itch.io/ryb'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['logic',],
        Mood: [],
        Issues: [],
        Tags: [ 'low plot', 'free',"rj bundle",  ],
    },
    {
        Title: 'Hidden in 8-Bit',
        Review: '8-bit nostalgia hidden object. Janky.',
        Post: '',
        Rating: 2,
        Link: [['Itchio','https://simsoftgames.itch.io/hidden-in-8-bit'],],
        Gameplay: ['puzzle', 'hidden object', ],
        Platform: ['Browser', ],
        Genre: [],
        Mood: [],
        Issues: [],
        Tags: ['low plot', 'free', ],
    },
    {
        Title: 'Lofty',
        Review: 'Janky perspective puzzles.',
        Post: '',
        Rating: 2,
        Link: [['Itchio','https://devonwiersma.itch.io/lofty'],],
        Gameplay: ['exploration', 'puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['logic',],
        Mood: [],
        Issues: [],
        Tags: [ 'short','low plot', 'free', ],
    },
    {
        Title: 'Finders',
        Review: 'Janky hidden object game.',
        Post: '',
        Rating: 2,
        Link: [['Itchio','https://duskchilder.itch.io/finders'],],
        Gameplay: ['puzzle', 'hidden object', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['logic', ],
        Mood: [],
        Issues: [],
        Tags: ['low plot', ],
    },
    {
        Title: 'Umbragram',
        Review: 'A tiny indie puzzle game about placing cubes to create 2D shadows. Very simple and sparse, it doesn\'t even have a save button, but I had fun.',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://alts.itch.io/umbragram'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['logic',],
        Mood: [],
        Issues: [],
        Tags: [ 'low plot', ],
    },
    {
        Title: 'Magical Diary: Horse Hall',
        Review: 'Super fun and surprisingly well written visual novel/dating sim/life sim where you play a new girl at not!Hogwarts. Has cute f/f options including an aroace girl.',
        Post: '',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/211340/Magical_Diary_Horse_Hall/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],['Itchio','https://hanakogames.itch.io/magical-diary-horse-hall'],],
        Gameplay: ['simulation', 'visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['romance', 'comedy', 'slice of life', 'adventure', 'fantasy','narrative', ],
        Mood: ['happy', 'cute', ],
        Issues: [],
        Tags: ['m/f', 'f/f', 'queer', 'female protag','aromantic/asexual' ],
    },
    {
        Title: 'Under Leaves',
        Review: 'Pretty but repetitive nature themed hidden objects,',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://circusatos.itch.io/under-leaves'],],
        Gameplay: ['puzzle', 'hidden object', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: [],
        Mood: ['gentle', ],
        Issues: [],
        Tags: ['beautiful', 'low plot', ],
    },
    {
        Title: 'Spring Falls',
        Review: 'Gentle, pretty puzzles about moving water to plants. Didn\'t entirely click with me but I had fun for a while and other people love it.',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://sparsegamedev.itch.io/spring-falls'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', 'iOS', ],
        Genre: ['logic',],
        Mood: ['gentle', ],
        Issues: [],
        Tags: [ 'beautiful', 'low plot',"rj bundle",  ],
    },
    {
        Title: 'reky',
        Review: 'Well made, elegant path-finding puzzles.',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://beyondthosehills.itch.io/reky'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', 'iOS',"Android" ],
        Genre: ['logic',],
        Mood: [],
        Issues: [],
        Tags: [ 'low plot', "rj bundle", ],
    },
    {
        Title: 'Word Forward',
        Review: 'adequate word-finding game. A bit janky.',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://rocketshippark.itch.io/word-forward'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['word game',],
        Mood: [],
        Issues: [],
        Tags: [ 'low plot', "rj bundle", ],
    },
    {
        Title: 'plant daddy',
        Review: 'Cute, simple, low-poly plant raising sim. ',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://overfull.itch.io/plantdaddy'],],
        Gameplay: ['sandbox', 'simulation'],
        Platform: ['Mac', 'Windows', 'Linux','Browser', ],
        Genre: [],
        Mood: ['cute', ],
        Issues: [],
        Tags: ['short','low plot',"rj bundle",  ],
    },
    {
        Title: 'adjacency',
        Review: 'Create shapes with colours. Hurt my brain in a good way :)',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://sleepymacaw.itch.io/adjacency'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['logic',],
        Mood: [ ],
        Issues: ['difficult', ],
        Tags: ['low plot', "rj bundle", ],
    },
    
    {
        Title: 'Undertale',
        Review: 'A very good rpg I found completely unplayable because my reaction speed is too slow.',
        Post: '',
        Rating: 3,
        Link: [['GOG','https://www.gog.com/game/undertale'],['Steam','https://store.steampowered.com/app/391540/Undertale/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['exploration', 'combat', "rpg"],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'comedy', 'action', 'adventure', 'fantasy', ],
        Mood: ['bittersweet', 'cute', ],
        Issues: ['death', 'dexterity/timing', ],
        Tags: ['f/f', 'non-binary', 'queer', ],
    },
    {
        Title: 'STAR WARS - Knights of the Old Republic',
        Review: 'Old Bioware RPG set in the star wars universe. I never finished it but had fun for a while.',
        Post: '',
        Rating: 3,
        Link: [['GOG','https://www.gog.com/game/star_wars_knights_of_the_old_republic'],['Steam','https://store.steampowered.com/app/32370/STAR_WARS__Knights_of_the_Old_Republic/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['exploration', 'combat',"rpg" ],
        Platform: ['Mac', 'Windows',"Xbox", ],
        Genre: ['narrative', 'romance', 'comedy', 'action', 'adventure', 'fantasy', 'science fiction', ],
        Mood: ['bittersweet', ],
        Issues: ['dexterity/timing', ],
        Tags: ['m/f', 'f/f', 'queer', 'female protag', 'gender choice', ],
    },
    {
        Title: 'We Know the Devil',
        Review: 'Brilliant, understated queer visual novel about three teens stuck at a religious camp where you literally confront the devil. Has dark aspects but is ultimately very optimistic and cathartic.',
        Post: 'https://alias-sqbr.dreamwidth.org/565019.html',
        Rating: 5,
        Link: [['Itchio','https://pillowfight.itch.io/we-know-the-devil'],['Steam','https:https://store.steampowered.com/app/435300/We_Know_the_Devil/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['narrative', 'romance', 'mystery', 'horror', 'fantasy', ],
        Mood: ['dark', 'bittersweet', ],
        Issues: ['violence',],
        Tags: ['f/f', 'queer', 'female protag', 'binary trans',],
    },
    {
        Title: 'Date Warp',
        Review: 'Flawed but enjoyable dating sim.',
        Post: 'https://alias-sqbr.dreamwidth.org/565019.html',
        Rating: 3,
        Link: [['Itchio','https://hanakogames.itch.io/date-warp'],['Steam','https://store.steampowered.com/app/301380/Date_Warp/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'comedy', 'mystery', 'fantasy', 'science fiction', ],
        Mood: ['bittersweet', ],
        Issues: [],
        Tags: ['m/f', 'm/m', 'polyamory', 'queer', 'female protag', ],
    },
    {
        Title: 'Graveyard Keeper',
        Review: 'Fun as a crafting game but the tone and premise was too gloomy/macabre for me.',
        Post: '',
        Rating: 2,
        Link: [['Steam','https://store.steampowered.com/app/599140/Graveyard_Keeper/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['crafting', 'survival', 'farming', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'comedy', 'fantasy', 'historical', ],
        Mood: ['dark', 'bittersweet', ],
        Issues: ['death', ],
        Tags: [],
    },
    {
        Title: 'World\'s Dawn',
        Review: 'A cute and inoffensive but kinda dull and cheaply made Harvest Moon/Stardew Valley style game.',
        Post: '',
        Rating: 2,
        Link: [['Steam','https://store.steampowered.com/app/432010/Worlds_Dawn/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['crafting', 'farming', ],
        Platform: ['Windows', ],
        Genre: ['narrative', 'romance', 'comedy', 'slice of life', 'fantasy', ],
        Mood: ['happy', 'cute', 'gentle', ],
        Issues: [],
        Tags: ['m/f', 'f/f', 'm/m', 'queer', 'female protag', 'gender choice', ],
    },
    {
        Title: 'ABZU',
        Review: 'A gentle and beautiful ocean exploration game with simple puzzles and a slow, ambiguous plot. Requires some hand eye coordination in parts.',
        Post: '',
        Rating: 4,
        Link: [['GOG','https://www.gog.com/game/abzu'],['Steam','https://store.steampowered.com/app/384190/ABZU/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['exploration', ],
        Platform: ['Windows', ],
        Genre: ['narrative', 'fantasy', 'science fiction', ],
        Mood: ['bittersweet', 'mysterious', 'cute', 'gentle', ],
        Issues: [],
        Tags: ['beautiful', ],
    },
    {
        Title: 'Dr. Langeskov, The Tiger, and The Terribly Cursed Emerald: A Whirlwind Heist',
        Review: 'A short, free, funny walking sim type game about games.',
        Post: '',
        Rating: 5,
        Link: [['Itchio','https://crowscrowscrows.itch.io/dr-langeskov-the-tiger-and-the-terribly-cursed-emerald-a-whirlwind-heist'],['Steam','https://store.steampowered.com/app/409160/Dr_Langeskov_The_Tiger_and_The_Terribly_Cursed_Emerald_A_Whirlwind_Heist/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['exploration', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['comedy', 'fantasy','narrative' ],
        Mood: [],
        Issues: [],
        Tags: ['free', ],
    },
    {
        Title: 'My Time At Portia',
        Review: 'Great crafting/exploration game. Some platforming and combat I found doable.',
        Post: 'https://steamcommunity.com/linkfilter/?url=https://alias-sqbr.dreamwidth.org/734630.html',
        Rating: 4,
        Link: [['GOG','https://www.gog.com/game/my_time_at_portia'],['Steam','https://store.steampowered.com/app/666140/My_Time_At_Portia/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['crafting', 'survival', 'farming', 'exploration', 'combat', 'platformer', "rpg"],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['romance', 'comedy', 'slice of life', 'action', 'adventure', 'science fiction', 'narrative',],
        Mood: ['happy', 'cute', 'gentle', ],
        Issues: ['dexterity/timing', ],
        Tags: ['m/f', 'f/f', 'm/m', 'queer', 'female protag', 'gender choice', ],
    },
    {
        Title: 'Terraria',
        Review: 'Exploring, crafting, and combat in 2D. A lot of fun, and the combat is generally pretty easy/avoidable. Unfortunate issues with race and gender.',
        Post: 'https://alias-sqbr.dreamwidth.org/801277.html',
        Rating: 4,
        Link: [['GOG','https://www.gog.com/game/terraria'],['Steam','https://store.steampowered.com/app/105600/Terraria/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['sandbox', 'crafting', 'survival', 'exploration', 'combat', "rpg"],
        Platform: ['Mac', 'Windows', 'Linux', "iOS","Android","Xbox",],
        Genre: ['action', 'adventure', 'fantasy', 'science fiction', ],
        Mood: [],
        Issues: ['problematic', 'dexterity/timing', ],
        Tags: ['female protag', 'gender choice', ],
    },
    {
        Title: 'Gone Home',
        Review: 'Exploration game, you play a woman who comes back from a trip and explores her empty family home figuring out what\'s been going on in everyone\'s lives. Surprisingly affecting queer subplot.',
        Post: '',
        Rating: 5,
        Link: [['GOG','https://www.gog.com/game/gone_home'],['Steam','https://store.steampowered.com/app/232430/Gone_Home/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['exploration', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'historical', ],
        Mood: ['bittersweet', 'mysterious', 'gentle', ],
        Issues: [],
        Tags: ['queer', 'female protag', ],
    },
    {
        Title: 'Slime Rancher',
        Review: 'Fun, cute game about exploring and farming with weird little alien slimes. Requires minor dexterity.',
        Post: '',
        Rating: 5,
        Link: [['GOG','https://www.gog.com/game/slime_rancher'],['Steam','https://store.steampowered.com/app/433340/Slime_Rancher/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['crafting', 'farming', 'exploration', 'combat', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'comedy', 'action', 'adventure', 'fantasy', 'science fiction', ],
        Mood: ['happy', 'cute', 'gentle', ],
        Issues: ['dexterity/timing', ],
        Tags: ['queer', 'female protag', ],
    },
    {
        Title: 'Stardew Valley',
        Review: 'Mostly a farming sim, but has friendship and romance paths with the villagers, including m/m and f/f. Great fun!',
        Post: '',
        Rating: 5,
        Link: [['GOG','https://www.gog.com/game/stardew_valley'],['Steam','https://store.steampowered.com/app/413150/Stardew_Valley/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['crafting', 'farming', 'exploration', 'combat', "rpg"],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'comedy', 'slice of life', 'fantasy', ],
        Mood: ['happy', 'cute', 'gentle', ],
        Issues: [],
        Tags: ['m/f', 'f/f', 'm/m', 'queer', 'female protag', 'gender choice', ],
    },
    {
        Title: 'Starbound',
        Review: 'Exploration/mining game, like Minecraft or Terraria. Cute, lots to do. Ungendered protagonist, as I recall.',
        Post: '',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/211820/Starbound/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],['GOG','https://www.gog.com/game/starbound']],
        Gameplay: ['sandbox', 'crafting', 'survival', 'exploration', 'combat',"rpg" ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'comedy', 'action', 'adventure', 'horror', 'fantasy', 'science fiction', ],
        Mood: [],
        Issues: ['dexterity/timing', ],
        Tags: ['non-binary', 'female protag', 'gender choice', ],
    },
    {
        Title: 'Subnautica',
        Review: 'Great exploration/survival game, does have some scary parts and I had to get help for some of the fiddlier sections due to clumsiness and poor reaction times.',
        Post: '',
        Rating: 5,
        Link: [['Steam','https://store.steampowered.com/app/264710/Subnautica/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['exploration', 'survival'],
        Platform: ['Mac', 'Windows', ],
        Genre: ['narrative', 'mystery', 'horror', 'science fiction', ],
        Mood: ['mysterious', 'gentle', ],
        Issues: ['death', 'scary', 'dexterity/timing', ],
        Tags: ['beautiful', ],
    },
    {
        Title: 'Dear Esther',
        Review: 'Beautiful and melancholy exploration game about death and loss. Not a happy story but immersive and interesting.',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/203810/Dear_Esther/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['exploration', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['narrative', 'mystery', ],
        Mood: ['sad', 'bittersweet', 'gentle', ],
        Issues: ['death', ],
        Tags: ['short','beautiful', ],
    },
    {
        Title: 'Yonder: The Cloud Catcher Chronicles',
        Review: 'A fun and gentle exploration and crafting game with no combat. Doesn\'t have a lot to it in terms of plot or characters, but I enjoyed wandering around aimlessly picking flowers',
        Post: '',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/580200/Yonder_The_Cloud_Catcher_Chronicles/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['farming', 'exploration', ],
        Platform: ['Windows', ],
        Genre: ['narrative', 'slice of life', 'fantasy', ],
        Mood: ['happy', 'cute', 'gentle', ],
        Issues: [],
        Tags: ['beautiful', 'female protag', 'gender choice', ],
    },
    {
        Title: 'Verdant Skies',
        Review: 'A slightly shonky but fun and diverse Stardew Valley in Space. Includes aroace, polyamorous, trans, and non-binary love interests.',
        Post: 'https://alias-sqbr.dreamwidth.org/754271.html',
        Rating: 4,
        Link: [['Itchio','https://howlingmoonsoftware.itch.io/verdant-skies'],['Steam','https://store.steampowered.com/app/730050/Verdant_Skies/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['simulation', 'visual novel',"farming" ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'comedy', 'slice of life', 'science fiction', ],
        Mood: ['happy', 'cute', 'gentle', ],
        Issues: [],
        Tags: ['m/f', 'f/f', 'm/m', 'non-binary', 'polyamory', 'queer', 'female protag','binary trans','aromantic/asexual', 'gender choice',"rj bundle",  ],
    },
    {
        Title: 'Kindred Spirits on the Roof',
        Review: 'A well made f/f romance game, I found some parts squicky about consent.',
        Post: 'https://alias-sqbr.dreamwidth.org/633920.html',
        Rating: 3,
        Link: [['GOG','https://www.gog.com/game/kindred_spirits_on_the_roof'],['Steam','https://store.steampowered.com/app/402620/Kindred_Spirits_on_the_Roof/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'comedy', 'slice of life', 'fantasy', ],
        Mood: ['happy', 'cute', 'gentle', ],
        Issues: ['non-consent', 'problematic', 'sex/nudity'],
        Tags: ['f/f', 'queer', 'female protag', ],
    },
    {
        Title: 'Hustle Cat',
        Review: 'Great light fantasy, about a teen whose pronouns you choose (including "they" option) who gets a job at a cafe whose employees are cursed to turn into cats. Male and female love interests, all great.',
        Post: 'https://alias-sqbr.dreamwidth.org/608098.html',
        Rating: 5,
        Link: [['Itchio','https://datenighto.itch.io/hustle-cat'],['Steam','https://store.steampowered.com/app/453340/Hustle_Cat/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['narrative', 'romance', 'comedy', 'slice of life', 'fantasy', ],
        Mood: ['happy', 'cute', ],
        Issues: [],
        Tags: ['m/f', 'f/f', 'm/m', 'non-binary', 'queer','female protag', 'gender choice', ],
    },
    {
        Title: 'OZMAFIA!!',
        Review: 'I liked some parts of this but one path (Robin) triggered me so badly I haven\'t played any more. I\'ve been told to avoid Manboy but that none of the other routes should be triggering.',
        Post: 'https://alias-sqbr.dreamwidth.org/717558.html',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/303290/OZMAFIA/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', ],
        Platform: ['Windows', ],
        Genre: ['narrative', 'romance', 'comedy', 'adventure', 'fantasy', ],
        Mood: [],
        Issues: ['non-consent', 'problematic', ],
        Tags: ['m/f', 'female protag', ],
    },
    {
        Title: 'Brilliant Shadows - Part One of the Book of Gray Magic',
        Review: 'Pretty enjoyable coming of age visual novel about a young lesbian necromancer in a vaguely feudal fantasy setting. Has some weird edges.',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/409920/Brilliant_Shadows__Part_One_of_the_Book_of_Gray_Magic/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', ],
        Platform: ['Windows', 'Linux', ],
        Genre: ['narrative', 'adventure', 'fantasy', ],
        Mood: [],
        Issues: [],
        Tags: ['f/f', 'queer', 'female protag', ],
    },
    {
        Title: 'Hakuoki',
        Review: 'Great dating sim about the Edo Era of Japan. Lots of history but also sexy vampire samurai. Divided into Kyoto Winds and Edo Blossoms. I am not sure how the mobile version works.',
        Post: 'https://alias-sqbr.dreamwidth.org/672333.html',
        Rating: 5,
        Link: [['Steam','https://store.steampowered.com/bundle/6421/IFI_Hakuoki_Kyoto_Winds__Edo_Blossoms_Bundle/'],],
        Gameplay: ['visual novel', ],
        Platform: ['Windows', "iOS","Android"],
        Genre: ['narrative', 'romance', 'action', 'adventure', 'horror', 'fantasy', 'historical', ],
        Mood: ['bittersweet', ],
        Issues: ['death', 'scary', 'non-consent', 'problematic', 'violence',],
        Tags: ['m/f', 'female protag', ],
    },
    {
        Title: 'Nightshade',
        Review: '',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/512180/Nightshade/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', ],
        Platform: ['Windows', "Switch"],
        Genre: ['narrative', 'romance', 'action', 'adventure', 'historical', ],
        Mood: ['bittersweet', ],
        Issues: ['unplayed','sex/nudity'],
        Tags: ['m/f', 'female protag',  ],
    },
    {
        Title: 'Nameless ~The one thing you must recall~',
        Review: 'This is a very enjoyable dating sim about a lonely teenage Korean girl who relies on her dolls for companionship in her empty house...and then they come to life as cute boys! I was worried I\'d find the premise too silly but once I got my head around it found the Toy Story-esque emotional arcs surprisingly affecting. It reminded me of the way Labyrinth used dolls and fairtytales coming to life as a metaphor for adolescent mixed feelings about the changes of adulthood, including sex. In the end the focus is more on the protagonist\'s emotional arc than the romances, and the ending, while happy, left me writing fixit fic, but I still really enjoyed it. Be warned that the plot goes to some dark places, especially in the bad endings. But it\'s also quite funny, with a lot of cute platonic relationships and swoony romances.',
        Post: 'https://alias-sqbr.dreamwidth.org/693056.html',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/337930/Nameless_The_one_thing_you_must_recall/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['narrative', 'romance', 'slice of life', 'comedy', 'fantasy', ],
        Mood: [],
        Issues: ["non-consent",],
        Tags: ['m/f', 'female protag', ],
    },
    {
        Title: 'Cinders',
        Review: 'Beautiful and well written visual novel/dating sim retelling of Cinderella. Very heterosexual but gives the "ugly" sisters and stepmother more complex characterisation.',
        Post: '',
        Rating: 4,
        Link: [['GOG','https://www.gog.com/game/cinders'],['Steam','https://store.steampowered.com/app/293680/Cinders/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'fantasy', ],
        Mood: [],
        Issues: [],
        Tags: ['beautiful', 'm/f', 'female protag', ],
    },
    {
        Title: 'The Confines Of The Crown',
        Review: 'Fun fantasy intrigue romance about the female bodyguard of a prince. Cute m/f paths, very minor f/f, unfortunate treatment of trans character.',
        Post: 'https://alias-sqbr.dreamwidth.org/486413.html',
        Rating: 3,
        Link: [['Itchio','https://hanakogames.itch.io/the-confines-of-the-crown'],['Steam','https://store.steampowered.com/app/356530/The_Confines_Of_The_Crown/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'action', 'comedy', 'fantasy', ],
        Mood: [],
        Issues: ["problematic"],
        Tags: ['m/f', 'female protag', ],
    },
    {
        Title: 'Hatoful Boyfriend',
        Review: 'Everyone\'s favourite pigeon dating sim. It\'s pretty great, but I was way oversold on the f/f. Darker than it looks!',
        Post: '',
        Rating: 5,
        Link: [['GOG','https://www.gog.com/game/hatoful_boyfriend'],['Steam','https://store.steampowered.com/app/310080/Hatoful_Boyfriend/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'slice of life', 'horror', 'comedy', 'fantasy', 'science fiction', ],
        Mood: ['happy', 'dark', 'bittersweet', ],
        Issues: ["death",'cheesy','violence',],
        Tags: ['m/f', 'female protag', ],
    },
    {
        Title: 'Amnesia: Memories',
        Review: 'Moderately entertaining otome game. A fair proportion of my enjoyment was horrified laughter, you die a LOT. Consent issues.',
        Post: 'https://alias-sqbr.dreamwidth.org/605657.html',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/865820/Psychedelica_of_the_Black_Butterfly/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', ],
        Platform: ['Windows', ],
        Genre: ['narrative', 'romance', 'mystery', 'fantasy', ],
        Mood: ['bittersweet', 'mysterious', ],
        Issues: ["non-consent",],
        Tags: ['m/f', 'female protag', ],
    },
    {
        Title: 'Psychedelica of the Black Butterfly',
        Review: 'Exploration of grief and moving on, more focus on story than romance and has some sad endings. You can skip the shooting minigame.',
        Post: 'https://alias-sqbr.dreamwidth.org/725386.html',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/865820/Psychedelica_of_the_Black_Butterfly/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'mystery', 'fantasy', ],
        Mood: ['bittersweet', ],
        Issues: ["death"],
        Tags: ['beautiful', 'm/f', 'female protag', ],
    },
    {
        Title: 'Dream Daddy: A Dad Dating Simulator',
        Review: 'A fluffy, funny, diverse dating sim where you\'re a single dad and can date other single dads. A bit emotionally hollow, and iffy on queer stuff.',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/654880/Dream_Daddy_A_Dad_Dating_Simulator/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'slice of life', 'comedy', ],
        Mood: ['happy', ],
        Issues: ["problematic",'cheesy',],
        Tags: ['m/m', "queer",'binary trans'],
    },
    {
        Title: 'Analogue: A Hate Story',
        Review: 'A confronting and affecting visual novel untangling a tragedy. The "white American explores sexism using Korean culture" premise is a bit unfortunate but it\'s very good for what it is.',
        Post: '',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/209370/Analogue_A_Hate_Story/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'mystery', 'science fiction', ],
        Mood: ['dark', 'bittersweet', 'mysterious', ],
        Issues: ["problematic","death"],
        Tags: ['f/f', 'm/f',"gender choice",'queer', ],
    },
    {
        Title: 'Magical Otoge Ciel',
        Review: 'I ran out of momentum on this but it seemed like a cute dating sim.',
        Post: '',
        Rating: 1,
        Link: [['Steam','https://store.steampowered.com/app/521470/Magical_Otoge_Ciel/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'adventure', 'comedy', 'fantasy', ],
        Mood: ['happy', ],
        Issues: ['unplayed',],
        Tags: ['m/f', 'female protag',  'free', ],
    },
    {
        Title: 'Dandelion - Wishes brought to you',
        Review: 'Good m/f dating sim let down a little by the time management aspect.',
        Post: 'https://alias-sqbr.dreamwidth.org/710353.html',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/321290/Dandelion__Wishes_brought_to_you/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['simulation', 'visual novel', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['narrative', 'romance', 'slice of life', 'adventure', 'comedy', 'fantasy', ],
        Mood: ['happy', 'bittersweet', ],
        Issues: ["non-consent"],
        Tags: ['m/f', 'female protag', ],
    },
    {
        Title: 'Rose of Winter',
        Review: 'Cute and lightly funny, short and not very deep. One path has a bittersweet end.',
        Post: '',
        Rating: 2,
        Link: [['Itchio','https://pillowfight.itch.io/rose-of-winter'],['Steam','https://store.steampowered.com/app/540880/Rose_of_Winter/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'adventure', 'comedy', 'fantasy', ],
        Mood: ['happy', 'bittersweet', 'cute', ],
        Issues: [],
        Tags: ['m/f', 'female protag', ],
    },
    {
        Title: 'one night, hot springs',
        Review: 'Lovely visual novel about a trans woman going to a hot springs with friends.',
        Post: '',
        Rating: 5,
        Link: [['Itchio','https://npckc.itch.io/one-night-hot-springs'],['Steam','https://store.steampowered.com/app/917680/one_night_hot_springs/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'slice of life', ],
        Mood: ['happy', 'bittersweet', 'cute', ],
        Issues: [],
        Tags: ['short','female protag','queer','binary trans' ],
    },
    {
        Title: 'Backstage Pass',
        Review: 'An enjoyable dating/life sim about a makeup artist in her first year of college. Has a f/f route, and an aroace guy.',
        Post: 'https://alias-sqbr.dreamwidth.org/689301.html',
        Rating: 4,
        Link: [['Itchio','https://sakevisual.itch.io/backstage-pass'],['Steam','https://store.steampowered.com/app/288220/Backstage_Pass/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', 'simulation', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'romance', 'comedy',"slice of life", ],
        Mood: ['happy', ],
        Issues: [],
        Tags: ['f/f', 'm/f', 'female protag', 'aromantic/asexual',"queer"],
    },
    {
        Title: 'Botanica: Into the Unknown Collector\'s Edition',
        Review: 'Pretty, good natured hidden object games about a female biologist who falls into another world and tries to figure her way back',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/626780/Botanica_Into_the_Unknown_Collectors_Edition/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: [ 'puzzle', "hidden object", "point and click", ],
        Platform: ['Windows', ],
        Genre: ['narrative', 'adventure', 'science fiction', ],
        Mood: ['mysterious', ],
        Issues: [],
        Tags: ['female protag', ],
    },
    {
        Title: 'Heaven\'s Vault',
        Review: '',
        Post: '',
        Rating: 2,
        Link: [['Steam','https://store.steampowered.com/app/774201/Heavens_Vault/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['exploration', 'puzzle', ],
        Platform: ['Windows', ],
        Genre: ['narrative', 'adventure', 'fantasy', 'science fiction', ],
        Mood: ['bittersweet', 'mysterious', ],
        Issues: ['unplayed',],
        Tags: ['beautiful', 'female protag',  ],
    },
    {
        Title: 'Hidden Folks',
        Review: 'Fun "Where\'s Wally" style puzzles where you have to find people and things in a big picture, but animated. Some of the early ones had some unfortunate racial stereotypes.',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://adriaan.itch.io/hidden-folks'],['Steam','https://store.steampowered.com/app/435400/Hidden_Folks/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['hidden object', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['comedy', ],
        Mood: ['cute', ],
        Issues: [],
        Tags: ["rj bundle","low plot" ],
    },
    {
        Title: 'Enigmatis 2: The Mists of Ravenwood',
        Review: 'Supernatural thriller hidden object game with a female protagonist investigating mysterious disappearances at a park.',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/284770/Enigmatis_2_The_Mists_of_Ravenwood/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['point and click', 'puzzle', 'hidden object', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'horror', 'adventure', 'fantasy', ],
        Mood: [ 'dark', 'mysterious', ],
        Issues: ['scary',],
        Tags: ['female protag', ],
    },
    {
        Title: 'SpaceChem',
        Review: 'Clever puzzle game where you have to create paths for atoms to follow so they become the right molecules. More computer science than chemistry, gets VERY difficult.',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://zachtronics.itch.io/spacechem'],['Steam','https://store.steampowered.com/app/92800/SpaceChem/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['science fiction','logic', 'narrative' ],
        Mood: [],
        Issues: ["difficult"],
        Tags: [],
    },
    {
        Title: 'realMyst: Masterpiece Edition',
        Review: 'Walk around version of the classic puzzle game (with a slideshow version if you prefer). Graphics are dated but the worlds are still very atmospheric and the puzzles are great.',
        Post: '',
        Rating: 4,
        Link: [['GOG','https://www.gog.com/game/real_myst_masterpiece_edition'],['Steam','https://store.steampowered.com/app/244430/realMyst_Masterpiece_Edition/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['exploration', 'point and click', 'puzzle', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['narrative', 'adventure', 'mystery', 'fantasy', 'science fiction', ],
        Mood: ['bittersweet', 'mysterious', 'gentle', ],
        Issues: [],
        Tags: ['beautiful', ],
    },
    {
        Title: 'Message Quest',
        Review: 'A puzzle game about a lazy messenger in a fantasy world trying to avoid doing his quest.',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/408280/Message_Quest/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['point and click', 'puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'adventure', 'comedy', 'fantasy', ],
        Mood: ['happy', 'cute', 'gentle', ],
        Issues: [],
        Tags: ['beautiful', ],
    },
    {
        Title: 'Broken Sword: Director\'s Cut',
        Review: 'Nicely revamped 90s noir-ish point and click adventure game.',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/57640/Broken_Sword_Directors_Cut/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['point and click', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'adventure', 'mystery', 'comedy', 'fantasy', ],
        Mood: ['mysterious', ],
        Issues: [],
        Tags: ['female protag', ],
    },
    {
        Title: 'Escape Rosecliff Island',
        Review: 'Hidden object puzzle game. No plot.',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/3600/Escape_Rosecliff_Island/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['hidden object', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['horror', ],
        Mood: ['dark', 'mysterious', ],
        Issues: [],
        Tags: ['low plot', ],
    },
    {
        Title: 'Nightmares from the Deep: The Cursed Heart',
        Review: 'A fun hidden object game but the Caribbean is disconcertingly white.',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/259740/Nightmares_from_the_Deep_The_Cursed_Heart/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', 'hidden object', "point and click", ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative','horror', 'mystery', 'fantasy', 'science fiction', ],
        Mood: ['dark', 'mysterious', ],
        Issues: ['scary', ],
        Tags: [],
    },
    {
        Title: 'Gorogoa',
        Review: 'Absolutely gorgeous, unique puzzle game. Required some minor dexterity/timing.',
        Post: '',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/557600/Gorogoa/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],['GOG','https://www.gog.com/game/gorogoa'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['narrative', 'mystery', 'fantasy', ],
        Mood: ['bittersweet', 'gentle', ],
        Issues: ['dexterity/timing',],
        Tags: [ 'beautiful', ],
    },
    {
        Title: 'Opus Magnum',
        Review: 'Great puzzle game about designing automata to create chemical molecules. My favourite Zachlike by far. Plot is minimal but fun fantasy.',
        Post: '',
        Rating: 4,
        Link: [['Itchio','https://zachtronics.itch.io/opus-magnum'],['Steam','https://store.steampowered.com/app/558990/Opus_Magnum/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle'],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'fantasy','logic'  ],
        Mood: ['happy', ],
        Issues: [],
        Tags: ['designer',],
    },
    {
        Title: 'Broken Age',
        Review: 'Beautiful and funny puzzle/adventure game. Ending is a bit meh but still an overall great game.',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/232790/Broken_Age/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['point and click', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'horror', 'mystery', 'comedy', 'fantasy', ],
        Mood: ['bittersweet', ],
        Issues: [],
        Tags: ['beautiful'],
    },
    {
        Title: 'Grim Fandango Remastered',
        Review: 'Revamped 90s noir-ish point and click adventure game. Fun for a while, but got so frustrating I just watched a Let\'s Play.',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/316790/Grim_Fandango_Remastered/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['point and click', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'horror', 'mystery', 'comedy', 'fantasy', ],
        Mood: ['bittersweet'],
        Issues: [],
        Tags: [],
    },
    {
        Title: 'The Room 2',
        Review: 'Some of the puzzles were a bit unintuitive or dull but overall it was a lot of fun, atmospheric and aesthetically enchanting, like playing with an antique puzzle box.',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/425580/The_Room_Two/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Windows', ],
        Genre: ['horror', 'mystery', 'fantasy', ],
        Mood: [ 'dark', 'bittersweet', 'mysterious', ],
        Issues: ['scary',],
        Tags: ['low plot', 'beautiful',],
    },
    {
        Title: 'Her Story',
        Review: 'It\'s a game about database searching, woo! WAIT NO IT\'S ACTUALLY GOOD. Twisty, tropey murder mystery.',
        Post: '',
        Rating: 2,
        Link: [['Steam','https://store.steampowered.com/app/368370/Her_Story/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['mystery', 'narrative'],
        Mood: ['dark', 'bittersweet', 'mysterious', ],
        Issues: ["problematic","death"],
        Tags: ['female protag', ],
    },
    {
        Title: 'Globesweeper',
        Review: 'Like minesweeper, but on a globe. Ok.',
        Post: '',
        Rating: 2,
        Link: [['Steam','https://store.steampowered.com/app/982220/Globesweeper/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['logic',],
        Mood: [],
        Issues: [],
        Tags: [ 'low plot', ],
    },
    {
        Title: 'Hexcells Plus',
        Review: 'A better minesweeper with none of the guessing and multiple lives. Also, hexagonal and quite pretty!',
        Post: '',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/271900/Hexcells_Plus/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['logic',],
        Mood: [],
        Issues: [],
        Tags: [ 'low plot', ],
    },
    {
        Title: 'Hexcells Infinite',
        Review: 'A better minesweeper with none of the guessing and multiple lives. Also, hexagonal and quite pretty!',
        Post: '',
        Rating: 5,
        Link: [['Steam','https://store.steampowered.com/app/304410/Hexcells_Infinite/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['logic',],
        Mood: [],
        Issues: [],
        Tags: [ 'low plot', ],
    },
    {
        Title: 'Tametsi',
        Review: 'A great simple puzzle game, with no guessing. Minesweeper-esque proximity location combined with different colours, tile shapes, and extra information keep it varied and fun.',
        Post: '',
        Rating: 5,
        Link: [['Steam','https://store.steampowered.com/app/709920/Tametsi/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Windows', ],
        Genre: ['logic',],
        Mood: [],
        Issues: [],
        Tags: [ 'low plot', ],
    },
    {
        Title: 'Hexcells',
        Review: 'A better minesweeper with none of the guessing and multiple lives. Also, hexagonal and quite pretty!',
        Post: '',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/265890/Hexcells/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['logic',],
        Mood: [],
        Issues: [],
        Tags: [ 'low plot', ],
    },
    {
        Title: 'Delete',
        Review: 'A minimalist, enjoyable take on Minesweeper, with some clever and challenging twists',
        Post: '',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/773670/Delete/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['logic',],
        Mood: [],
        Issues: [],
        Tags: [ 'low plot', ],
    },
    {
        Title: 'Alphabear: Hardcover Edition',
        Review: 'A desktop version of the phone game. A great, cute word game. Still a bit grindy, but not as much as the mobile version.',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/644080/Alphabear_Hardcover_Edition/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['word game'],
        Mood: [],
        Issues: [],
        Tags: [ 'low plot', ],
    },
    {
        Title: 'Everyday Genius: SquareLogic',
        Review: 'A fun logic puzzle game combining sudoko-esque elimination with simple maths, with near infinitely many puzzles of varying difficult.',
        Post: '',
        Rating: 5,
        Link: [['Steam','https://store.steampowered.com/app/32150/Everyday_Genius_SquareLogic/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Windows', ],
        Genre: ['logic', ],
        Mood: [],
        Issues: [],
        Tags: ['low plot', ],
    },
    {
        Title: 'Cross Set',
        Review: 'A slight spin on sudoku. Not the best game ever but I had fun with it.',
        Post: '',
        Rating: 2,
        Link: [['Steam','https://store.steampowered.com/app/415400/Cross_Set/'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['logic',],
        Mood: [],
        Issues: [],
        Tags: [ 'low plot', ],
    },
    {
        Title: 'Pajama Sam: No Need to Hide When It\'s Dark Outside',
        Review: 'Cute kids point and click adventure game.',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/283960/Pajama_Sam_No_Need_to_Hide_When_Its_Dark_Outside/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ["point and click",'puzzle', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['comedy', 'fantasy', ],
        Mood: ['happy', 'cute', 'gentle', ],
        Issues: ['cheesy',],
        Tags: [ ],
    },
    {
        Title: 'Engare',
        Review: 'A gorgeous but flawed geometric design puzzle game inspired by islamic art, with tools to create your own designs. Could be frustrating to use sometimes, and is quite short, but is unique',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/415170/Engare/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['logic',],
        Mood: [],
        Issues: [],
        Tags: [ 'beautiful', 'low plot'],
    },
    {
        Title: 'The Eyes of Ara',
        Review: 'Myst-like puzzle game, it was fun for a while but I ended up getting bored and frustrated.',
        Post: '',
        Rating: 2,
        Link: [['Steam','https://store.steampowered.com/app/454250/The_Eyes_of_Ara/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: [ 'puzzle', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['mystery', 'fantasy','narrative', ],
        Mood: ['dark', 'mysterious', ],
        Issues: [],
        Tags: [ ],
    },
    {
        Title: 'Phoenix Wright: Ace Attorney Trilogy',
        Review: 'Fun murder mysteries and court case puzzles. Haven\'t played yet, though I enjoyed the DS version.',
        Post: '',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/787480/Phoenix_Wright_Ace_Attorney_Trilogy/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle','visual novel', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'mystery', 'comedy', ],
        Mood: [],
        Issues: [],
        Tags: [],
    },
    {
        Title: 'Paint it Back',
        Review: 'Silly pun filled picross game about fixing vanished paintings. The puns and silly art really add to the experience, though some of the jokes are unfortunate and the UI is pretty bad in places. Has some extra challenges I found interesting as a game dev and player, overall has much more variety and better aesthetics than your average picross game. The 2016 american politics section has not aged well.',
        Post: '',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/385250/Paint_it_Back/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['comedy','logic', ],
        Mood: [],
        Issues: ['cheesy',],
        Tags: [  'low plot', ],
    },
    {
        Title: 'Pictopix',
        Review: 'Picross style puzzle game, simple but fun.',
        Post: '',
        Rating: 5,
        Link: [['Steam','https://store.steampowered.com/app/568320/Pictopix/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['logic',],
        Mood: [],
        Issues: [],
        Tags: [ 'designer', 'low plot', ],
    },
    {
        Title: 'Contraption Maker',
        Review: 'Cute fun puzzle game about making ridiculous machines to solve puzzles. Got a bit hard for me, too much spatial thinking',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/241240/Contraption_Maker/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: [],
        Mood: [],
        Issues: [],
        Tags: [ 'designer','low plot', ],
    },
    {
        Title: 'Crayon Physics Deluxe',
        Review: 'Flawed but interesting puzzle game where you draw objects to solve puzzles using physics',
        Post: '',
        Rating: 2,
        Link: [['Steam','https://store.steampowered.com/app/26900/Crayon_Physics_Deluxe/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', ],
        Genre: [],
        Mood: [],
        Issues: [],
        Tags: [ 'designer','low plot', ],
    },
    {
        Title: 'Scribblenauts Unlimited',
        Review: 'Solve people\'s problems by creating/editing objects. Fun, but a bit iffy on gender.',
        Post: '',
        Rating: 2,
        Link: [['Steam','https://store.steampowered.com/app/218680/Scribblenauts_Unlimited/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Windows', ],
        Genre: ['comedy', ],
        Mood: ['cute', ],
        Issues: ["problematic"],
        Tags: [ 'low plot', 'cheesy', ],
    },
    {
        Title: 'The Tiny Bang Story',
        Review: 'A cute, pretty, and surreal puzzle/hidden object game whose main flaw for me was that it was just slightly too difficult, and had some platformer parts I found challenging.',
        Post: '',
        Rating: 2,
        Link: [['Steam','https://store.steampowered.com/app/96000/The_Tiny_Bang_Story/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: [ 'puzzle', 'hidden object', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative','fantasy', ],
        Mood: ['cute', ],
        Issues: [],
        Tags: [ 'low plot', ],
    },
    {
        Title: 'Long Live The Queen',
        Review: 'Fiendishly difficult but fun raising sim, where you make choices for a new queen and try not to have her die (or at least hit all the death options). Has f/f options though I never made it that far.',
        Post: '',
        Rating: 3,
        Link: [['Itchio','https://hanakogames.itch.io/long-live-the-queen'],['Steam','https://store.steampowered.com/app/251990/Long_Live_The_Queen/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['visual novel', 'simulation', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative','romance', 'comedy', 'fantasy', ],
        Mood: ['dark', ],
        Issues: ["difficult","death"],
        Tags: ['m/f', 'f/f', 'female protag', 'queer',],
    },
    {
        Title: 'Abyss: The Wraiths of Eden',
        Review: 'A good, if dark, hidden object game.',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/284710/Abyss_The_Wraiths_of_Eden/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', 'hidden object', "point and click", ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative','horror', 'mystery', 'fantasy', 'science fiction', ],
        Mood: [ 'dark', 'mysterious', ],
        Issues: ['scary',"death"],
        Tags: [ ],
    },
    {
        Title: 'My Brother Rabbit',
        Review: '',
        Post: '',
        Rating: 2,
        Link: [['Steam','https://store.steampowered.com/app/855640/My_Brother_Rabbit/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', "hidden object", "point and click", ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'adventure', 'fantasy', ],
        Mood: ['bittersweet', 'cute', ],
        Issues: ['unplayed',],
        Tags: [],
    },
    {
        Title: 'The Room',
        Review: 'Some of the puzzles were a bit unintuitive or dull but overall it was a lot of fun, atmospheric and aesthetically enchanting, like playing with an antique puzzle box.',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/288160/The_Room/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Windows', ],
        Genre: ['horror', 'mystery', 'fantasy', ],
        Mood: [ 'dark', 'bittersweet', 'mysterious', ],
        Issues: ['scary',],
        Tags: ['low plot', 'beautiful',],
    },
    {
        Title: 'Portal 2',
        Review: 'Awesome portal based puzzle games, clever puzzles and really well written with a great dark sense of humour. Requires some dexterity, I think I needed some help at one point.',
        Post: '',
        Rating: 5,
        Link: [['Steam','https://store.steampowered.com/app/620/Portal_2/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['platformer','puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'horror', 'comedy', 'science fiction', ],
        Mood: ['dark', ],
        Issues: ['dexterity/timing', ],
        Tags: ['female protag', ],
    },
    {
        Title: 'Portal',
        Review: 'Awesome portal based puzzle games, clever puzzles and really well written with a great dark sense of humour. Requires some dexterity, I think I needed some help at one point.',
        Post: '',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/620/Portal_2/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['platformer', 'puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'horror', 'comedy', 'science fiction', ],
        Mood: ['dark', ],
        Issues: ['dexterity/timing',],
        Tags: ['female protag', ],
    },
    {
        Title: 'Grim Legends: The Forsaken Bride',
        Review: 'Enjoyable enough hidden object game.',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/284850/Grim_Legends_The_Forsaken_Bride/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', "hidden object", "point and click", ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'horror', 'mystery', 'fantasy', ],
        Mood: ['mysterious', ],
        Issues: [],
        Tags: ['female protag', ],
    },
    {
        Title: 'Botanica: Earthbound Collector\'s Edition',
        Review: 'Pretty, good natured hidden object games about a female biologist who falls into another world and tries to figure her way back',
        Post: '',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/758610/Botanica_Earthbound_Collectors_Edition/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: [ 'puzzle', "hidden object", "point and click", ],
        Platform: ['Windows', ],
        Genre: ['narrative', 'adventure', 'science fiction', ],
        Mood: ['mysterious', ],
        Issues: [],
        Tags: ['female protag', ],
    },
    {
        Title: 'Obduction',
        Review: 'Great puzzle/adventure game from the creators of Myst',
        Post: '',
        Rating: 4,
        Link: [['GOG','https://www.gog.com/game/obduction'],['Steam','https://store.steampowered.com/app/306760/Obduction/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: [ 'exploration', 'puzzle', ],
        Platform: ['Mac', 'Windows', ],
        Genre: ['narrative', 'mystery', 'fantasy', 'science fiction', ],
        Mood: ['bittersweet', 'mysterious', ],
        Issues: [],
        Tags: ['beautiful', ],
    },
    {
        Title: 'The Gardens Between',
        Review: 'I\'m still playing this but it\'s a really lovely, gentle puzzle game with an interesting if mind-bending time travel mechanic.',
        Post: '',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/600990/The_Gardens_Between/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['adventure', 'fantasy', ],
        Mood: ['cute','gentle'],
        Issues: [],
        Tags: ['female protag','beautiful' ],
    },
    {
        Title: 'Meanwhile: An Interactive Comic Book',
        Rating: 2,
        Link: [['Steam','https://store.steampowered.com/app/714980/Meanwhile_An_Interactive_Comic_Book/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'comedy', 'science fiction', ],
        Mood: ['bittersweet', ],
        Issues: [],
        Tags: [],
        Review: '',
        Post: '',
    },
    {
        Title: 'Putt-Putt Travels Through Time',
        Rating: 2,
        Link: [['Steam','https://store.steampowered.com/app/294670/PuttPutt_Travels_Through_Time/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],['GOG','g'],],
        Gameplay: ['exploration', 'puzzle', "point and click", ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'comedy', ],
        Mood: ['happy', ],
        Issues: ['cheesy'],
        Tags: [ ],
        Review: '',
        Post: '',
    },
    {
        Title: 'J.U.L.I.A.: Among the Stars',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/257690/JULIA_Among_the_Stars/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['exploration', 'puzzle', "point and click", ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['narrative', 'mystery', 'science fiction', ],
        Mood: ['dark', 'bittersweet', 'mysterious', ],
        Issues: [],
        Tags: ['female protag', ],
        Review: 'An interesting, plotty Czech science fiction puzzle game with some of the feel of a hidden object game. Dark in parts',
        Post: '',
    },
    {
        Title: 'LOOP: A Tranquil Puzzle Game',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/370150/LOOP_A_Tranquil_Puzzle_Game/?snr=1_1056_1055_1056_1057&curator_clanid=35349987'],],
        Gameplay: ['puzzle'],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['logic',],
        Mood: [],
        Issues: [],
        Tags: ['low plot', ],
        Review: 'A great puzzle game about rearranging pieces to form loops.',
        Post: '',
    },
    {
        Title: 'Discolored',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/933860/Discolored/?curator_clanid=35349987'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['mystery', 'fantasy', ],
        Mood: ["mysterious"],
        Issues: [],
        Tags: ['short', ],
        Review: 'This is a fun, eerily atmospheric, interesting little point and click puzzle game. Some of the puzzles were frustrating but it\'s overall pretty good',
        Post: '',
    },
    {
        Title: 'Evergarden',
        Rating: 3,
        Link: [['Steam','https://store.steampowered.com/app/576500/Evergarden/'],],
        Gameplay: ['puzzle', ],
        Platform: ['Mac', 'Windows', 'Linux', ],
        Genre: ['fantasy','logic', ],
        Mood: ['bittersweet', ],
        Issues: [],
        Tags: ['low plot','beautiful', ],
        Review: 'A gentle, beautiful matching game where you replay slightly randomised versions of the same basic puzzle to unlock skills and secrets',
        Post: '',
    },
    {
        Title: '7 Billion Humans',
        Rating: 4,
        Link: [['Steam','https://store.steampowered.com/app/792100/7_Billion_Humans'],['GOG','https://www.gog.com/game/7_billion_humans'],['Itchio','https://tomorrowcorporation.itch.io/7-billion-humans'],],
        Gameplay: ['puzzle',], 
        Genre: ['comedy', 'science fiction', 'logic',],
        Platform: ['Mac', 'Windows', 'Linux', 'Switch', 'iOS',"Android" ],
        Mood: ['dark', ],
        Issues: [],
        Tags: ['low plot',],
        Review: "A fun, darkly humourous, challenging parallel programming puzzle game. The plot doesn't make a lot of sense but you don't play this kind of game for the plot",
        Post: '',
    },
]